#!/usr/bin/env bash

# -------------------------------
display_help()
{
    echo "Script used to show latest versions of virtual environments. Needed to"
    echo ""
    echo "- Find out what version to use when updating environment"
    echo "- Find out what version to use to send slimming jobs" 
    echo ""
    echo "-n: Number of lines to print, default 5"
}
# -------------------------------
get_opts()
{
    while getopts :hf:n:s: option; do 
        case "${option}" in
            h)  
                display_help
                exit 0
                ;;  
            n)  JOB_NAME=${OPTARG};;
            s)  SAMPLE_NAME=${OPTARG};;
           \?)  echo "Invalid option: -${OPTARG}"
                display_help
                exit 1
                ;;  
            :)  echo "$0: Arguments needed"
                display_help
                exit 1
                ;;  
        esac
    done
}
# -------------------------------
check_env()
{
    which dirac-dms-user-lfns > /dev/null 2>&1
    if [[ $? -ne 0 ]];then
        echo "Dirac not available, run lb_dirac to be in the right environment"
        exit 1
    fi

    if [[ -z $LXNAME ]];then
        echo "LXNAME variable not set"
        exit 1
    fi

    if [[ -z $JOB_NAME ]];then
        echo "Job name not passed"
        exit 1
    fi

    if [[ -z $SAMPLE_NAME]];then
        echo "Sample name not passed"
        exit 1
    fi
}
# -------------------------------
remove_lfns()
{
    LFN_PATH=/lhcb/user/${LXNAME:0:1}/$LXNAME/$JOB_NAME"_"$SAMPLE_NAME 
    dirac-dms-user-lfns -b $LFN_PATH > /dev/null 2>&1
    LFN_LIST=lhcb-user-${LXNAME:0:1}-$LXNAME-run3-venv.lfns
    NFILES=$(wc -l $LFN_LIST)
    if [[ $NFILES -eq 0 ]];then
        echo "No LFNs were found in $LFN_PATH"
        exit 1
    fi

    echo "Removing $NFILES LFNs"

    dirac-dms-remove-files $LFN_LIST
}
# -------------------------------
get_opts "$@"
check_env
remove_lfns

