
from typing import Self, overload
import numpy

class RResultPtr:
    def GetValue(self) -> int: ...

class RCutFlowReport:
    def Print(self) -> None: ...

class RNode:
    def Define(self, name: str, definition: str) -> Self: ...
    def Redefine(self, name: str, definition: str) -> Self: ...
    def Count(self) -> RResultPtr: ...
    def GetColumnNames(self) -> list[str]: ...
    def Range(self, end : int, begin : int = 0) -> 'RNode': ...
    def Report(self) -> RCutFlowReport: ...
    @overload
    def Filter(self, expression : str) -> 'RNode': ...
    @overload
    def Filter(self, expression : str, name : str) -> 'RNode': ...
    def AsNumpy(self, columns : list[str] = []) -> dict[str, numpy.ndarray]: ...

class Experimental:
    @staticmethod
    def FromSpec(jsonFile : str) -> RNode: ...
