# Taken from:
# https://gitlab.cern.ch/gitlabci-examples/build_docker_image/-/blob/master/.gitlab-ci.yml?ref_type=heads#L54
stages:
  - test
  - build-environment
  - build-analysis
environment:
  stage: build-environment
  image: registry.cern.ch/quay.io/buildah/stable
  before_script:
    - sed -i 's/^driver = .*/driver = "vfs"/' /etc/containers/storage.conf
    - echo "$CI_REGISTRY_PASSWORD" | buildah login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - buildah bud  -t $CI_REGISTRY_IMAGE:v3.0.0 -f docker/env.Dockerfile
    - buildah push    $CI_REGISTRY_IMAGE:v3.0.0
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.0\.0$/
analysis:
  stage: build-analysis
  image: registry.cern.ch/quay.io/buildah/stable
  before_script:
    - sed -i 's/^driver = .*/driver = "vfs"/' /etc/containers/storage.conf
    - echo "$CI_REGISTRY_PASSWORD" | buildah login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - buildah bud  -t $CI_REGISTRY_IMAGE:9c48b60bc -f docker/ana.Dockerfile
    - buildah push    $CI_REGISTRY_IMAGE:9c48b60bc
  only:
    - issue-002 
