#!/usr/bin/env bash

#--------------------------------------
set_vars()
{
    echo "Turning off multithreading"
    export MKL_NUM_THREADS=1
    export NUMEXPR_NUM_THREADS=1
    export OMP_NUM_THREADS=1
    export OPENBLAS_NUM_THREADS=1
}
#--------------------------------------
rename_paths()
{
    ENVNAME=dcheck
    ORGPATH=/home/acampove/Test/venv

    for FILEPATH in $(grep --files-with-matches --binary-files=without-match -r $ORGPATH/$ENVNAME $PWD/$ENVNAME);do
	echo $ORGPATH "--->"
	echo $PWD     "  in  "  $FILEPATH
	echo ""
	sed -i "s|$ORGPATH|$PWD|g" $FILEPATH
    done
}
#--------------------------------------
DSET=$1
CONF=$2
NJOB=$3
IJOB=$4

set_vars
rename_paths

dcheck/run bash -c "filter_ntuples -d $DSET -c $CONF -n $NJOB -i $IJOB" 

