import numba
from _typeshed import Incomplete
from vector._methods import AzimuthalRhoPhi as AzimuthalRhoPhi, AzimuthalXY as AzimuthalXY, LongitudinalEta as LongitudinalEta, LongitudinalTheta as LongitudinalTheta, LongitudinalZ as LongitudinalZ, Momentum as Momentum, TemporalT as TemporalT, TemporalTau as TemporalTau
from vector.backends._numba import numba_modules as numba_modules
from vector.backends.object import AzimuthalObject as AzimuthalObject, AzimuthalObjectRhoPhi as AzimuthalObjectRhoPhi, AzimuthalObjectXY as AzimuthalObjectXY, LongitudinalObject as LongitudinalObject, LongitudinalObjectEta as LongitudinalObjectEta, LongitudinalObjectTheta as LongitudinalObjectTheta, LongitudinalObjectZ as LongitudinalObjectZ, MomentumObject2D as MomentumObject2D, MomentumObject3D as MomentumObject3D, MomentumObject4D as MomentumObject4D, TemporalObject as TemporalObject, TemporalObjectT as TemporalObjectT, TemporalObjectTau as TemporalObjectTau, VectorObject2D as VectorObject2D, VectorObject3D as VectorObject3D, VectorObject4D as VectorObject4D

def nan_to_num(x, copy: bool = True, nan: float = 0.0, posinf=None, neginf=None): ...
def is_azimuthaltype(typ): ...
def is_longitudinaltype(typ): ...
def is_temporaltype(typ): ...
def numba_aztype(typ): ...
def numba_ltype(typ): ...
def numba_ttype(typ): ...

class VectorObject2DType(numba.types.Type):
    instance_class = VectorObject2D
    azimuthaltype: Incomplete
    def __init__(self, azimuthaltype) -> None: ...

class MomentumObject2DType(VectorObject2DType):
    instance_class = MomentumObject2D
    name: Incomplete
    def __init__(self, azimuthaltype) -> None: ...

class VectorObject2DModel(numba.extending.models.StructModel):
    def __init__(self, dmm, fe_type) -> None: ...

def VectorObject2D_typeof(val, c): ...
def VectorObject2D_constructor_typer(context): ...
def MomentumObject2D_constructor_typer(context): ...
def VectorObject2D_constructor_impl(context, builder, sig, args): ...
def VectorObject2D_unbox(typ, obj, c): ...
def VectorObject2D_box(typ, val, c): ...

class VectorObject3DType(numba.types.Type):
    instance_class = VectorObject3D
    azimuthaltype: Incomplete
    longitudinaltype: Incomplete
    def __init__(self, azimuthaltype, longitudinaltype) -> None: ...

class MomentumObject3DType(VectorObject3DType):
    instance_class = MomentumObject3D
    name: Incomplete
    def __init__(self, azimuthaltype, longitudinaltype) -> None: ...

class VectorObject3DModel(numba.extending.models.StructModel):
    def __init__(self, dmm, fe_type) -> None: ...

def VectorObject3D_typeof(val, c): ...
def VectorObject3D_constructor_typer(context): ...
def MomentumObject3D_constructor_typer(context): ...
def VectorObject3D_constructor_impl(context, builder, sig, args): ...
def VectorObject3D_unbox(typ, obj, c): ...
def VectorObject3D_box(typ, val, c): ...

class VectorObject4DType(numba.types.Type):
    instance_class = VectorObject4D
    azimuthaltype: Incomplete
    longitudinaltype: Incomplete
    temporaltype: Incomplete
    def __init__(self, azimuthaltype, longitudinaltype, temporaltype) -> None: ...

class MomentumObject4DType(VectorObject4DType):
    instance_class = MomentumObject4D
    name: Incomplete
    def __init__(self, azimuthaltype, longitudinaltype, temporaltype) -> None: ...

class VectorObject4DModel(numba.extending.models.StructModel):
    def __init__(self, dmm, fe_type) -> None: ...

def VectorObject4D_typeof(val, c): ...
def VectorObject4D_constructor_typer(context): ...
def MomentumObject4D_constructor_typer(context): ...
def VectorObject4D_constructor_impl(context, builder, sig, args): ...
def VectorObject4D_unbox(typ, obj, c): ...
def VectorObject4D_box(typ, val, c): ...
def vector_obj_Azimuthal_xy(x, px, y, py, rho, pt, phi): ...
def vector_obj_Azimuthal_xpy(x, px, y, py, rho, pt, phi): ...
def vector_obj_Azimuthal_pxy(x, px, y, py, rho, pt, phi): ...
def vector_obj_Azimuthal_pxpy(x, px, y, py, rho, pt, phi): ...
def vector_obj_Azimuthal_rhophi(x, px, y, py, rho, pt, phi): ...
def vector_obj_Azimuthal_ptphi(x, px, y, py, rho, pt, phi): ...
def vector_obj_Longitudinal_z(z, pz, theta, eta): ...
def vector_obj_Longitudinal_pz(z, pz, theta, eta): ...
def vector_obj_Longitudinal_theta(z, pz, theta, eta): ...
def vector_obj_Longitudinal_eta(z, pz, theta, eta): ...
def vector_obj_Temporal_t(t, E, e, energy, tau, M, m, mass): ...
def vector_obj_Temporal_E(t, E, e, energy, tau, M, m, mass): ...
def vector_obj_Temporal_e(t, E, e, energy, tau, M, m, mass): ...
def vector_obj_Temporal_energy(t, E, e, energy, tau, M, m, mass): ...
def vector_obj_Temporal_tau(t, E, e, energy, tau, M, m, mass): ...
def vector_obj_Temporal_M(t, E, e, energy, tau, M, m, mass): ...
def vector_obj_Temporal_m(t, E, e, energy, tau, M, m, mass): ...
def vector_obj_Temporal_mass(t, E, e, energy, tau, M, m, mass): ...
def vector_obj(unrecognized_argument=None, x=None, px=None, y=None, py=None, rho=None, pt=None, phi=None, z=None, pz=None, theta=None, eta=None, t=None, E=None, e=None, energy=None, tau=None, M=None, m=None, mass=None): ...
def VectorObject2D_to_Vector2D(v): ...
def VectorObject2D_to_Vector3D(v): ...
def VectorObject2D_to_Vector4D(v): ...
def VectorObject3D_to_Vector2D(v): ...
def VectorObject3D_to_Vector3D(v): ...
def VectorObject3D_to_Vector4D(v): ...
def VectorObject4D_to_Vector2D(v): ...
def VectorObject4D_to_Vector3D(v): ...
def VectorObject4D_to_Vector4D(v): ...
def make_AzimuthalObjectXY(v): ...
def make_AzimuthalObjectRhoPhi(v): ...
def make_LongitudinalObjectZ(v): ...
def make_LongitudinalObjectZ_zero(v): ...
def make_LongitudinalObjectTheta(v): ...
def make_LongitudinalObjectTheta_zero(v): ...
def make_LongitudinalObjectEta(v): ...
def make_LongitudinalObjectEta_zero(v): ...
def make_TemporalObjectT(v): ...
def make_TemporalObjectT_zero(v): ...
def make_TemporalObjectTau(v): ...
def make_TemporalObjectTau_zero(v): ...

make_coordobject: Incomplete

def add_coordinate_change(vectortype, azcoordtype, lcoordtype, tcoordtype): ...

only_tcoordtype: Incomplete

def azimuthalxy_coord1(v): ...
def azimuthalxy_coord2(v): ...
def azimuthalrhophi_coord1(v): ...
def azimuthalrhophi_coord2(v): ...
def longitudinalz_coord1(v): ...
def longitudinaltheta_coord1(v): ...
def longitudinaleta_coord1(v): ...
def temporalt_coord1(v): ...
def temporaltau_coord1(v): ...

getcoord1: Incomplete
getcoord2: Incomplete
planar_properties: Incomplete
spatial_properties: Incomplete
lorentz_properties: Incomplete
lorentz_momentum_properties: Incomplete

def add_planar_property(vectortype, propertyname): ...
def add_spatial_property(vectortype, propertyname): ...
def add_lorentz_property(vectortype, propertyname): ...

planar_binary_methods: Incomplete
spatial_binary_methods: Incomplete
lorentz_binary_methods: Incomplete
general_binary_methods: Incomplete

def dimension_of(v): ...
def flavor_of(v1, v2): ...
def add_binary_method(vectortype, gn, methodname): ...

tolerance_methods: Incomplete

def add_tolerance_method(vectortype, methodname): ...
def add_isclose_method(vectortype): ...
def add_rotateZ(vectortype): ...
def add_transform2D(vectortype): ...
def VectorObject2DType_unit(v): ...
def VectorObject3DType_unit(v): ...
def VectorObject4DType_unit(v): ...
def VectorObject2DType_scale(v, factor): ...
def VectorObject3DType_scale(v, factor): ...
def VectorObject4DType_scale(v, factor): ...
def VectorObject34DType_scale2D(v, factor): ...
def VectorObject4DType_scale3D(v, factor): ...
def VectorObject34DType_cross(v1, v2): ...
def VectorObject34DType_rotateX(v, angle): ...
def VectorObject34DType_rotateY(v, angle): ...
def VectorObject34DType_rotate_axis(v, axis, angle): ...
def VectorObject34DType_rotate_euler(v, phi, theta, psi, order: str = 'zxz'): ...
def VectorObject34DType_rotate_nautical(v, yaw, pitch, roll): ...
def VectorObject34DType_rotate_quaternion(v, u, i, j, k): ...
def VectorObject34DType_transform3D(v, obj): ...
def VectorObject4DType_boost_p4(v, p4): ...
def VectorObject4DType_boost_beta3(v, beta3): ...
def VectorObject4DType_boost(v, booster): ...
def VectorObject4DType_boostCM_of_p4(v, p4): ...
def VectorObject4DType_boostCM_of_beta3(v, beta3): ...
def VectorObject4DType_boostCM_of(v, booster): ...
def add_boostXYZ(methodname): ...
def VectorObject4DType_to_beta3(v): ...
def VectorObject4DType_transform4D(v, obj): ...
def VectorObject4DType_is_timelike(v, tolerance: int = 0): ...
def VectorObject4DType_is_spacelike(v, tolerance: int = 0): ...
def VectorObject4DType_is_lightlike(v, tolerance: float = 1e-05): ...
def VectorObject234DType_neg2D(v): ...
def VectorObject34DType_neg3D(v): ...
def VectorObject4DType_neg4D(v): ...
def MomentumObject234DType_px(v): ...
def MomentumObject234DType_py(v): ...
def MomentumObject234DType_pt(v): ...
def MomentumObject234DType_pt2(v): ...
def MomentumObject34DType_pz(v): ...
def MomentumObject34DType_pseudorapidity(v): ...
def MomentumObject34DType_p(v): ...
def MomentumObject34DType_p2(v): ...
def MomentumObject4DType_E(v): ...
def MomentumObject4DType_energy(v): ...
def MomentumObject4DType_E2(v): ...
def MomentumObject4DType_energy2(v): ...
def MomentumObject4DType_M(v): ...
def MomentumObject4DType_mass(v): ...
def MomentumObject4DType_M2(v): ...
def MomentumObject4DType_mass2(v): ...
def MomentumObject4DType_transverse_energy(v): ...
def MomentumObject4DType_transverse_energy2(v): ...
def MomentumObject4DType_transverse_mass(v): ...
def MomentumObject4DType_transverse_mass2(v): ...
def numpy_absolute(v): ...
def numpy_square(v): ...
def numpy_sqrt(v): ...
def numpy_cbrt(v): ...
def numpy_power(v, expo): ...
def numpy_add(v1, v2): ...
def numpy_subtract(v1, v2): ...
def numpy_multiply(a, b): ...
def numpy_true_divide(a, b): ...
def numpy_negative(v): ...
def numpy_positive(v): ...
def numpy_matmul(v1, v2): ...
def operator_abs(v): ...
def operator_neg(v): ...
def operator_pos(v): ...
def operator_truth(v): ...
def operator_eq(v1, v2): ...
def operator_ne(v1, v2): ...
def operator_add(v1, v2): ...
def operator_sub(v1, v2): ...
def operator_mul(a, b): ...
def operator_truediv(a, b): ...
def operator_pow(a, b): ...
def operator_matmul(v1, v2): ...
