import awkward as ak
import functools
import types
import typing
from _typeshed import Incomplete
from vector._methods import Azimuthal as Azimuthal, AzimuthalRhoPhi as AzimuthalRhoPhi, AzimuthalXY as AzimuthalXY, Longitudinal as Longitudinal, LongitudinalEta as LongitudinalEta, LongitudinalTheta as LongitudinalTheta, LongitudinalZ as LongitudinalZ, Lorentz as Lorentz, LorentzMomentum as LorentzMomentum, Momentum as Momentum, Planar as Planar, PlanarMomentum as PlanarMomentum, Spatial as Spatial, SpatialMomentum as SpatialMomentum, Temporal as Temporal, TemporalT as TemporalT, TemporalTau as TemporalTau, Vector2D as Vector2D, Vector3D as Vector3D, Vector4D as Vector4D, VectorProtocol as VectorProtocol
from vector._typeutils import BoolCollection as BoolCollection, Protocol as Protocol, ScalarCollection as ScalarCollection
from vector.backends.numpy import VectorNumpy2D as VectorNumpy2D, VectorNumpy3D as VectorNumpy3D, VectorNumpy4D as VectorNumpy4D
from vector.backends.object import AzimuthalObjectRhoPhi as AzimuthalObjectRhoPhi, AzimuthalObjectXY as AzimuthalObjectXY, LongitudinalObjectEta as LongitudinalObjectEta, LongitudinalObjectTheta as LongitudinalObjectTheta, LongitudinalObjectZ as LongitudinalObjectZ, TemporalObjectT as TemporalObjectT, TemporalObjectTau as TemporalObjectTau, VectorObject2D as VectorObject2D, VectorObject3D as VectorObject3D, VectorObject4D as VectorObject4D

ArrayOrRecord = typing.TypeVar('ArrayOrRecord', bound=ak.Array | ak.Record)
Array = typing.TypeVar('Array')
behavior: typing.Any

class CoordinatesAwkward:
    lib: types.ModuleType

class AzimuthalAwkward(CoordinatesAwkward, Azimuthal):
    @classmethod
    def from_fields(cls, array: ak.Array) -> AzimuthalAwkward: ...
    @classmethod
    def from_momentum_fields(cls, array: ak.Array) -> AzimuthalAwkward: ...

class LongitudinalAwkward(CoordinatesAwkward, Longitudinal):
    @classmethod
    def from_fields(cls, array: ak.Array) -> LongitudinalAwkward: ...
    @classmethod
    def from_momentum_fields(cls, array: ak.Array) -> LongitudinalAwkward: ...

class TemporalAwkward(CoordinatesAwkward, Temporal):
    @classmethod
    def from_fields(cls, array: ak.Array) -> TemporalAwkward: ...
    @classmethod
    def from_momentum_fields(cls, array: ak.Array) -> TemporalAwkward: ...

class AzimuthalAwkwardXY(AzimuthalAwkward, AzimuthalXY):
    x: Incomplete
    y: Incomplete
    def __init__(self, x: typing.Any, y: typing.Any) -> None: ...
    @property
    def elements(self) -> tuple[ArrayOrRecord, ArrayOrRecord]: ...

class AzimuthalAwkwardRhoPhi(AzimuthalAwkward, AzimuthalRhoPhi):
    rho: Incomplete
    phi: Incomplete
    def __init__(self, rho: typing.Any, phi: typing.Any) -> None: ...
    @property
    def elements(self) -> tuple[ArrayOrRecord, ArrayOrRecord]: ...

class LongitudinalAwkwardZ(LongitudinalAwkward, LongitudinalZ):
    z: Incomplete
    def __init__(self, z: typing.Any) -> None: ...
    @property
    def elements(self) -> tuple[ArrayOrRecord]: ...

class LongitudinalAwkwardTheta(LongitudinalAwkward, LongitudinalTheta):
    theta: Incomplete
    def __init__(self, theta: typing.Any) -> None: ...
    @property
    def elements(self) -> tuple[ArrayOrRecord]: ...

class LongitudinalAwkwardEta(LongitudinalAwkward, LongitudinalEta):
    eta: Incomplete
    def __init__(self, eta: typing.Any) -> None: ...
    @property
    def elements(self) -> tuple[ArrayOrRecord]: ...

class TemporalAwkwardT(TemporalAwkward, TemporalT):
    t: Incomplete
    def __init__(self, t: typing.Any) -> None: ...
    @property
    def elements(self) -> tuple[ArrayOrRecord]: ...

class TemporalAwkwardTau(TemporalAwkward, TemporalTau):
    tau: Incomplete
    def __init__(self, tau: typing.Any) -> None: ...
    @property
    def elements(self) -> tuple[ArrayOrRecord]: ...

class AwkwardProtocol(Protocol):
    def __getitem__(self, where: typing.Any) -> float | ak.Array | ak.Record | None: ...

class _lib(typing.NamedTuple):
    module: types.ModuleType
    nplike: ak._nplikes.numpy_like.NumpyLike
    def __eq__(self, other: typing.Any) -> bool: ...
    def __ne__(self, other: typing.Any) -> bool: ...
    def __getattr__(self, name: str) -> typing.Any: ...

class VectorAwkward:
    @property
    def lib(self): ...

class bind(functools.partial):
    def __call__(self, *args: typing.Any, **keywords: typing.Any) -> typing.Any: ...

class awkward_transform:
    func: Incomplete
    def __init__(self, func: typing.Callable) -> None: ...
    def __call__(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Callable: ...

class VectorAwkward2D(VectorAwkward, Planar, Vector2D):
    @property
    def azimuthal(self) -> AzimuthalAwkward: ...

class MomentumAwkward2D(PlanarMomentum, VectorAwkward2D):
    @property
    def azimuthal(self) -> AzimuthalAwkward: ...

class VectorAwkward3D(VectorAwkward, Spatial, Vector3D):
    @property
    def azimuthal(self) -> AzimuthalAwkward: ...
    @property
    def longitudinal(self) -> LongitudinalAwkward: ...

class MomentumAwkward3D(SpatialMomentum, VectorAwkward3D):
    @property
    def azimuthal(self) -> AzimuthalAwkward: ...
    @property
    def longitudinal(self) -> LongitudinalAwkward: ...

class VectorAwkward4D(VectorAwkward, Lorentz, Vector4D):
    @property
    def azimuthal(self) -> AzimuthalAwkward: ...
    @property
    def longitudinal(self) -> LongitudinalAwkward: ...
    @property
    def temporal(self) -> TemporalAwkward: ...

class MomentumAwkward4D(LorentzMomentum, VectorAwkward4D):
    @property
    def azimuthal(self) -> AzimuthalAwkward: ...
    @property
    def longitudinal(self) -> LongitudinalAwkward: ...
    @property
    def temporal(self) -> TemporalAwkward: ...

class VectorArray2D(VectorAwkward2D, ak.Array):
    def allclose(self, other: VectorProtocol, rtol: ScalarCollection = 1e-05, atol: ScalarCollection = 1e-08, equal_nan: BoolCollection = False) -> BoolCollection: ...

class VectorRecord2D(VectorAwkward2D, ak.Record): ...

class VectorArray3D(VectorAwkward3D, ak.Array):
    def allclose(self, other: VectorProtocol, rtol: ScalarCollection = 1e-05, atol: ScalarCollection = 1e-08, equal_nan: BoolCollection = False) -> BoolCollection: ...

class VectorRecord3D(VectorAwkward3D, ak.Record): ...

class VectorArray4D(VectorAwkward4D, ak.Array):
    def allclose(self, other: VectorProtocol, rtol: ScalarCollection = 1e-05, atol: ScalarCollection = 1e-08, equal_nan: BoolCollection = False) -> BoolCollection: ...

class VectorRecord4D(VectorAwkward4D, ak.Record): ...

class MomentumArray2D(MomentumAwkward2D, ak.Array):
    def allclose(self, other: VectorProtocol, rtol: ScalarCollection = 1e-05, atol: ScalarCollection = 1e-08, equal_nan: BoolCollection = False) -> BoolCollection: ...

class MomentumRecord2D(MomentumAwkward2D, ak.Record): ...

class MomentumArray3D(MomentumAwkward3D, ak.Array):
    def allclose(self, other: VectorProtocol, rtol: ScalarCollection = 1e-05, atol: ScalarCollection = 1e-08, equal_nan: BoolCollection = False) -> BoolCollection: ...

class MomentumRecord3D(MomentumAwkward3D, ak.Record): ...

class MomentumArray4D(MomentumAwkward4D, ak.Array):
    def allclose(self, other: VectorProtocol, rtol: ScalarCollection = 1e-05, atol: ScalarCollection = 1e-08, equal_nan: BoolCollection = False) -> BoolCollection: ...

class MomentumRecord4D(MomentumAwkward4D, ak.Record): ...
