import numpy
import typing
from _typeshed import Incomplete
from vector._methods import Azimuthal as Azimuthal, AzimuthalRhoPhi as AzimuthalRhoPhi, AzimuthalXY as AzimuthalXY, Longitudinal as Longitudinal, LongitudinalEta as LongitudinalEta, LongitudinalTheta as LongitudinalTheta, LongitudinalZ as LongitudinalZ, Lorentz as Lorentz, LorentzMomentum as LorentzMomentum, Planar as Planar, PlanarMomentum as PlanarMomentum, SameVectorType as SameVectorType, Spatial as Spatial, SpatialMomentum as SpatialMomentum, Temporal as Temporal, TemporalT as TemporalT, TemporalTau as TemporalTau, Vector as Vector, Vector2D as Vector2D, Vector3D as Vector3D, Vector4D as Vector4D, VectorProtocol as VectorProtocol
from vector._typeutils import FloatArray as FloatArray

class CoordinatesObject: ...
class AzimuthalObject(CoordinatesObject, Azimuthal): ...
class LongitudinalObject(CoordinatesObject, Longitudinal): ...
class TemporalObject(CoordinatesObject, Temporal): ...

class TupleXY(typing.NamedTuple):
    x: float
    y: float

class AzimuthalObjectXY(AzimuthalObject, AzimuthalXY, TupleXY):
    @property
    def elements(self) -> tuple[float, float]: ...

class TupleRhoPhi(typing.NamedTuple):
    rho: float
    phi: float

class AzimuthalObjectRhoPhi(AzimuthalObject, AzimuthalRhoPhi, TupleRhoPhi):
    @property
    def elements(self) -> tuple[float, float]: ...

class TupleZ(typing.NamedTuple):
    z: float

class LongitudinalObjectZ(LongitudinalObject, LongitudinalZ, TupleZ):
    @property
    def elements(self) -> tuple[float]: ...

class TupleTheta(typing.NamedTuple):
    theta: float

class LongitudinalObjectTheta(LongitudinalObject, LongitudinalTheta, TupleTheta):
    @property
    def elements(self) -> tuple[float]: ...

class TupleEta(typing.NamedTuple):
    eta: float

class LongitudinalObjectEta(LongitudinalObject, LongitudinalEta, TupleEta):
    @property
    def elements(self) -> tuple[float]: ...

class TupleT(typing.NamedTuple):
    t: float

class TemporalObjectT(TemporalObject, TemporalT, TupleT):
    @property
    def elements(self) -> tuple[float]: ...

class TupleTau(typing.NamedTuple):
    tau: float

class TemporalObjectTau(TemporalObject, TemporalTau, TupleTau):
    @property
    def elements(self) -> tuple[float]: ...

class VectorObject(Vector):
    lib = numpy
    def __eq__(self, other: typing.Any) -> typing.Any: ...
    def __ne__(self, other: typing.Any) -> typing.Any: ...
    def __abs__(self) -> float: ...
    def __add__(self, other: VectorProtocol) -> VectorProtocol: ...
    def __radd__(self, other: VectorProtocol) -> VectorProtocol: ...
    def __iadd__(self, other: VectorProtocol) -> SameVectorType: ...
    def __sub__(self, other: VectorProtocol) -> VectorProtocol: ...
    def __rsub__(self, other: VectorProtocol) -> VectorProtocol: ...
    def __isub__(self, other: VectorProtocol) -> SameVectorType: ...
    def __mul__(self, other: float) -> VectorProtocol: ...
    def __rmul__(self, other: float) -> VectorProtocol: ...
    def __imul__(self, other: float) -> SameVectorType: ...
    def __neg__(self) -> SameVectorType: ...
    def __pos__(self) -> SameVectorType: ...
    def __truediv__(self, other: float) -> VectorProtocol: ...
    def __rtruediv__(self, other: float) -> VectorProtocol: ...
    def __itruediv__(self, other: float) -> VectorProtocol: ...
    def __pow__(self, other: float) -> float: ...
    def __matmul__(self, other: VectorProtocol) -> float: ...
    def __array_ufunc__(self, ufunc: typing.Any, method: typing.Any, *inputs: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class VectorObject2D(VectorObject, Planar, Vector2D):
    azimuthal: AzimuthalObject
    @classmethod
    def from_xy(cls, x: float, y: float) -> VectorObject2D: ...
    @classmethod
    def from_rhophi(cls, rho: float, phi: float) -> VectorObject2D: ...
    def __init__(self, azimuthal: AzimuthalObject | None = None, **kwargs: float) -> None: ...
    def __array__(self) -> FloatArray: ...
    @property
    def x(self) -> float: ...
    @x.setter
    def x(self, x: float) -> None: ...
    @property
    def y(self) -> float: ...
    @y.setter
    def y(self, y: float) -> None: ...
    @property
    def rho(self) -> float: ...
    @rho.setter
    def rho(self, rho: float) -> None: ...
    @property
    def phi(self) -> float: ...
    @phi.setter
    def phi(self, phi: float) -> None: ...

class MomentumObject2D(PlanarMomentum, VectorObject2D):
    def __array__(self) -> FloatArray: ...
    @property
    def px(self) -> float: ...
    azimuthal: Incomplete
    @px.setter
    def px(self, px: float) -> None: ...
    @property
    def py(self) -> float: ...
    @py.setter
    def py(self, py: float) -> None: ...
    @property
    def pt(self) -> float: ...
    @pt.setter
    def pt(self, pt: float) -> None: ...

class VectorObject3D(VectorObject, Spatial, Vector3D):
    azimuthal: AzimuthalObject
    longitudinal: LongitudinalObject
    @classmethod
    def from_xyz(cls, x: float, y: float, z: float) -> VectorObject3D: ...
    @classmethod
    def from_xytheta(cls, x: float, y: float, theta: float) -> VectorObject3D: ...
    @classmethod
    def from_xyeta(cls, x: float, y: float, eta: float) -> VectorObject3D: ...
    @classmethod
    def from_rhophiz(cls, rho: float, phi: float, z: float) -> VectorObject3D: ...
    @classmethod
    def from_rhophitheta(cls, rho: float, phi: float, theta: float) -> VectorObject3D: ...
    @classmethod
    def from_rhophieta(cls, rho: float, phi: float, eta: float) -> VectorObject3D: ...
    def __init__(self, azimuthal: AzimuthalObject | None = None, longitudinal: LongitudinalObject | None = None, **kwargs: float) -> None: ...
    def __array__(self) -> FloatArray: ...
    @property
    def x(self) -> float: ...
    @x.setter
    def x(self, x: float) -> None: ...
    @property
    def y(self) -> float: ...
    @y.setter
    def y(self, y: float) -> None: ...
    @property
    def rho(self) -> float: ...
    @rho.setter
    def rho(self, rho: float) -> None: ...
    @property
    def phi(self) -> float: ...
    @phi.setter
    def phi(self, phi: float) -> None: ...
    @property
    def z(self) -> float: ...
    @z.setter
    def z(self, z: float) -> None: ...
    @property
    def theta(self) -> float: ...
    @theta.setter
    def theta(self, theta: float) -> None: ...
    @property
    def eta(self) -> float: ...
    @eta.setter
    def eta(self, eta: float) -> None: ...

class MomentumObject3D(SpatialMomentum, VectorObject3D):
    def __array__(self) -> FloatArray: ...
    @property
    def px(self) -> float: ...
    azimuthal: Incomplete
    @px.setter
    def px(self, px: float) -> None: ...
    @property
    def py(self) -> float: ...
    @py.setter
    def py(self, py: float) -> None: ...
    @property
    def pt(self) -> float: ...
    @pt.setter
    def pt(self, pt: float) -> None: ...
    @property
    def pz(self) -> float: ...
    longitudinal: Incomplete
    @pz.setter
    def pz(self, pz: float) -> None: ...

class VectorObject4D(VectorObject, Lorentz, Vector4D):
    azimuthal: AzimuthalObject
    longitudinal: LongitudinalObject
    temporal: TemporalObject
    @classmethod
    def from_xyzt(cls, x: float, y: float, z: float, t: float) -> VectorObject4D: ...
    @classmethod
    def from_xyztau(cls, x: float, y: float, z: float, tau: float) -> VectorObject4D: ...
    @classmethod
    def from_xythetat(cls, x: float, y: float, theta: float, t: float) -> VectorObject4D: ...
    @classmethod
    def from_xythetatau(cls, x: float, y: float, theta: float, tau: float) -> VectorObject4D: ...
    @classmethod
    def from_xyetat(cls, x: float, y: float, eta: float, t: float) -> VectorObject4D: ...
    @classmethod
    def from_xyetatau(cls, x: float, y: float, eta: float, tau: float) -> VectorObject4D: ...
    @classmethod
    def from_rhophizt(cls, rho: float, phi: float, z: float, t: float) -> VectorObject4D: ...
    @classmethod
    def from_rhophiztau(cls, rho: float, phi: float, z: float, tau: float) -> VectorObject4D: ...
    @classmethod
    def from_rhophithetat(cls, rho: float, phi: float, theta: float, t: float) -> VectorObject4D: ...
    @classmethod
    def from_rhophithetatau(cls, rho: float, phi: float, theta: float, tau: float) -> VectorObject4D: ...
    @classmethod
    def from_rhophietat(cls, rho: float, phi: float, eta: float, t: float) -> VectorObject4D: ...
    @classmethod
    def from_rhophietatau(cls, rho: float, phi: float, eta: float, tau: float) -> VectorObject4D: ...
    def __init__(self, azimuthal: AzimuthalObject | None = None, longitudinal: LongitudinalObject | None = None, temporal: TemporalObject | None = None, **kwargs: float) -> None: ...
    def __array__(self) -> FloatArray: ...
    @property
    def x(self) -> float: ...
    @x.setter
    def x(self, x: float) -> None: ...
    @property
    def y(self) -> float: ...
    @y.setter
    def y(self, y: float) -> None: ...
    @property
    def rho(self) -> float: ...
    @rho.setter
    def rho(self, rho: float) -> None: ...
    @property
    def phi(self) -> float: ...
    @phi.setter
    def phi(self, phi: float) -> None: ...
    @property
    def z(self) -> float: ...
    @z.setter
    def z(self, z: float) -> None: ...
    @property
    def theta(self) -> float: ...
    @theta.setter
    def theta(self, theta: float) -> None: ...
    @property
    def eta(self) -> float: ...
    @eta.setter
    def eta(self, eta: float) -> None: ...
    @property
    def t(self) -> float: ...
    @t.setter
    def t(self, t: float) -> None: ...
    @property
    def tau(self) -> float: ...
    @tau.setter
    def tau(self, tau: float) -> None: ...

class MomentumObject4D(LorentzMomentum, VectorObject4D):
    def __array__(self) -> FloatArray: ...
    @property
    def px(self) -> float: ...
    azimuthal: Incomplete
    @px.setter
    def px(self, px: float) -> None: ...
    @property
    def py(self) -> float: ...
    @py.setter
    def py(self, py: float) -> None: ...
    @property
    def pt(self) -> float: ...
    @pt.setter
    def pt(self, pt: float) -> None: ...
    @property
    def pz(self) -> float: ...
    longitudinal: Incomplete
    @pz.setter
    def pz(self, pz: float) -> None: ...
    @property
    def E(self) -> float: ...
    temporal: Incomplete
    @E.setter
    def E(self, E: float) -> None: ...
    @property
    def e(self) -> float: ...
    @e.setter
    def e(self, e: float) -> None: ...
    @property
    def energy(self) -> float: ...
    @energy.setter
    def energy(self, energy: float) -> None: ...
    @property
    def M(self) -> float: ...
    @M.setter
    def M(self, M: float) -> None: ...
    @property
    def m(self) -> float: ...
    @m.setter
    def m(self, m: float) -> None: ...
    @property
    def mass(self) -> float: ...
    @mass.setter
    def mass(self, mass: float) -> None: ...

@typing.overload
def obj(*, x: float, y: float) -> VectorObject2D: ...
@typing.overload
def obj(*, x: float, py: float) -> MomentumObject2D: ...
@typing.overload
def obj(*, px: float, y: float) -> MomentumObject2D: ...
@typing.overload
def obj(*, px: float, py: float) -> MomentumObject2D: ...
@typing.overload
def obj(*, rho: float, phi: float) -> VectorObject2D: ...
@typing.overload
def obj(*, pt: float, phi: float) -> MomentumObject2D: ...
@typing.overload
def obj(*, x: float, y: float, z: float) -> VectorObject3D: ...
@typing.overload
def obj(*, x: float, y: float, pz: float) -> MomentumObject3D: ...
@typing.overload
def obj(*, x: float, py: float, z: float) -> MomentumObject3D: ...
@typing.overload
def obj(*, x: float, py: float, pz: float) -> MomentumObject3D: ...
@typing.overload
def obj(*, px: float, y: float, z: float) -> MomentumObject3D: ...
@typing.overload
def obj(*, px: float, y: float, pz: float) -> MomentumObject3D: ...
@typing.overload
def obj(*, px: float, py: float, z: float) -> MomentumObject3D: ...
@typing.overload
def obj(*, px: float, py: float, pz: float) -> MomentumObject3D: ...
@typing.overload
def obj(*, rho: float, phi: float, z: float) -> VectorObject3D: ...
@typing.overload
def obj(*, rho: float, phi: float, pz: float) -> MomentumObject3D: ...
@typing.overload
def obj(*, pt: float, phi: float, z: float) -> MomentumObject3D: ...
@typing.overload
def obj(*, pt: float, phi: float, pz: float) -> MomentumObject3D: ...
@typing.overload
def obj(*, x: float, y: float, theta: float) -> VectorObject3D: ...
@typing.overload
def obj(*, x: float, py: float, theta: float) -> MomentumObject3D: ...
@typing.overload
def obj(*, px: float, y: float, theta: float) -> MomentumObject3D: ...
@typing.overload
def obj(*, px: float, py: float, theta: float) -> MomentumObject3D: ...
@typing.overload
def obj(*, rho: float, phi: float, theta: float) -> VectorObject3D: ...
@typing.overload
def obj(*, pt: float, phi: float, theta: float) -> MomentumObject3D: ...
@typing.overload
def obj(*, x: float, y: float, eta: float) -> VectorObject3D: ...
@typing.overload
def obj(*, x: float, py: float, eta: float) -> MomentumObject3D: ...
@typing.overload
def obj(*, px: float, y: float, eta: float) -> MomentumObject3D: ...
@typing.overload
def obj(*, px: float, py: float, eta: float) -> MomentumObject3D: ...
@typing.overload
def obj(*, rho: float, phi: float, eta: float) -> VectorObject3D: ...
@typing.overload
def obj(*, pt: float, phi: float, eta: float) -> MomentumObject3D: ...
@typing.overload
def obj(*, x: float, y: float, z: float, t: float) -> VectorObject4D: ...
@typing.overload
def obj(*, x: float, y: float, pz: float, t: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, py: float, z: float, t: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, py: float, pz: float, t: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, y: float, z: float, t: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, y: float, pz: float, t: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, py: float, z: float, t: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, py: float, pz: float, t: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, rho: float, phi: float, z: float, t: float) -> VectorObject4D: ...
@typing.overload
def obj(*, rho: float, phi: float, pz: float, t: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, pt: float, phi: float, z: float, t: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, pt: float, phi: float, pz: float, t: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, y: float, theta: float, t: float) -> VectorObject4D: ...
@typing.overload
def obj(*, x: float, py: float, theta: float, t: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, y: float, theta: float, t: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, py: float, theta: float, t: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, rho: float, phi: float, theta: float, t: float) -> VectorObject4D: ...
@typing.overload
def obj(*, pt: float, phi: float, theta: float, t: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, y: float, eta: float, t: float) -> VectorObject4D: ...
@typing.overload
def obj(*, x: float, py: float, eta: float, t: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, y: float, eta: float, t: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, py: float, eta: float, t: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, rho: float, phi: float, eta: float, t: float) -> VectorObject4D: ...
@typing.overload
def obj(*, pt: float, phi: float, eta: float, t: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, y: float, z: float, tau: float) -> VectorObject4D: ...
@typing.overload
def obj(*, x: float, y: float, pz: float, tau: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, py: float, z: float, tau: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, py: float, pz: float, tau: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, y: float, z: float, tau: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, y: float, pz: float, tau: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, py: float, z: float, tau: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, py: float, pz: float, tau: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, rho: float, phi: float, z: float, tau: float) -> VectorObject4D: ...
@typing.overload
def obj(*, rho: float, phi: float, pz: float, tau: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, ptau: float, phi: float, z: float, tau: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, ptau: float, phi: float, pz: float, tau: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, y: float, theta: float, tau: float) -> VectorObject4D: ...
@typing.overload
def obj(*, x: float, py: float, theta: float, tau: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, y: float, theta: float, tau: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, py: float, theta: float, tau: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, rho: float, phi: float, theta: float, tau: float) -> VectorObject4D: ...
@typing.overload
def obj(*, ptau: float, phi: float, theta: float, tau: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, y: float, eta: float, tau: float) -> VectorObject4D: ...
@typing.overload
def obj(*, x: float, py: float, eta: float, tau: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, y: float, eta: float, tau: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, py: float, eta: float, tau: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, rho: float, phi: float, eta: float, tau: float) -> VectorObject4D: ...
@typing.overload
def obj(*, ptau: float, phi: float, eta: float, tau: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, y: float, z: float, E: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, y: float, pz: float, E: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, py: float, z: float, E: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, py: float, pz: float, E: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, y: float, z: float, E: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, y: float, pz: float, E: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, py: float, z: float, E: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, py: float, pz: float, E: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, rho: float, phi: float, z: float, E: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, rho: float, phi: float, pz: float, E: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, pE: float, phi: float, z: float, E: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, pE: float, phi: float, pz: float, E: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, y: float, theta: float, E: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, py: float, theta: float, E: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, y: float, theta: float, E: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, py: float, theta: float, E: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, rho: float, phi: float, theta: float, E: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, pE: float, phi: float, theta: float, E: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, y: float, eta: float, E: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, py: float, eta: float, E: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, y: float, eta: float, E: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, py: float, eta: float, E: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, rho: float, phi: float, eta: float, E: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, pE: float, phi: float, eta: float, E: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, y: float, z: float, e: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, y: float, pz: float, e: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, py: float, z: float, e: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, py: float, pz: float, e: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, y: float, z: float, e: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, y: float, pz: float, e: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, py: float, z: float, e: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, py: float, pz: float, e: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, rho: float, phi: float, z: float, e: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, rho: float, phi: float, pz: float, e: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, pe: float, phi: float, z: float, e: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, pe: float, phi: float, pz: float, e: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, y: float, theta: float, e: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, py: float, theta: float, e: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, y: float, theta: float, e: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, py: float, theta: float, e: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, rho: float, phi: float, theta: float, e: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, pe: float, phi: float, theta: float, e: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, y: float, eta: float, e: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, py: float, eta: float, e: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, y: float, eta: float, e: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, py: float, eta: float, e: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, rho: float, phi: float, eta: float, e: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, pe: float, phi: float, eta: float, e: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, y: float, z: float, energy: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, y: float, pz: float, energy: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, py: float, z: float, energy: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, py: float, pz: float, energy: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, y: float, z: float, energy: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, y: float, pz: float, energy: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, py: float, z: float, energy: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, py: float, pz: float, energy: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, rho: float, phi: float, z: float, energy: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, rho: float, phi: float, pz: float, energy: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, pt: float, phi: float, z: float, energy: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, pt: float, phi: float, pz: float, energy: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, y: float, theta: float, energy: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, py: float, theta: float, energy: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, y: float, theta: float, energy: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, py: float, theta: float, energy: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, rho: float, phi: float, theta: float, energy: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, pt: float, phi: float, theta: float, energy: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, y: float, eta: float, energy: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, py: float, eta: float, energy: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, y: float, eta: float, energy: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, py: float, eta: float, energy: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, rho: float, phi: float, eta: float, energy: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, pt: float, phi: float, eta: float, energy: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, y: float, z: float, M: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, y: float, pz: float, M: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, py: float, z: float, M: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, py: float, pz: float, M: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, y: float, z: float, M: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, y: float, pz: float, M: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, py: float, z: float, M: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, py: float, pz: float, M: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, rho: float, phi: float, z: float, M: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, rho: float, phi: float, pz: float, M: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, pM: float, phi: float, z: float, M: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, pM: float, phi: float, pz: float, M: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, y: float, theta: float, M: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, py: float, theta: float, M: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, y: float, theta: float, M: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, py: float, theta: float, M: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, rho: float, phi: float, theta: float, M: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, pM: float, phi: float, theta: float, M: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, y: float, eta: float, M: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, py: float, eta: float, M: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, y: float, eta: float, M: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, py: float, eta: float, M: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, rho: float, phi: float, eta: float, M: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, pM: float, phi: float, eta: float, M: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, y: float, z: float, m: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, y: float, pz: float, m: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, py: float, z: float, m: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, py: float, pz: float, m: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, y: float, z: float, m: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, y: float, pz: float, m: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, py: float, z: float, m: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, py: float, pz: float, m: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, rho: float, phi: float, z: float, m: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, rho: float, phi: float, pz: float, m: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, pm: float, phi: float, z: float, m: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, pm: float, phi: float, pz: float, m: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, y: float, theta: float, m: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, py: float, theta: float, m: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, y: float, theta: float, m: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, py: float, theta: float, m: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, rho: float, phi: float, theta: float, m: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, pm: float, phi: float, theta: float, m: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, y: float, eta: float, m: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, py: float, eta: float, m: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, y: float, eta: float, m: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, py: float, eta: float, m: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, rho: float, phi: float, eta: float, m: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, pm: float, phi: float, eta: float, m: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, y: float, z: float, mass: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, y: float, pz: float, mass: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, py: float, z: float, mass: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, py: float, pz: float, mass: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, y: float, z: float, mass: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, y: float, pz: float, mass: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, py: float, z: float, mass: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, py: float, pz: float, mass: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, rho: float, phi: float, z: float, mass: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, rho: float, phi: float, pz: float, mass: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, pt: float, phi: float, z: float, mass: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, pt: float, phi: float, pz: float, mass: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, y: float, theta: float, mass: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, py: float, theta: float, mass: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, y: float, theta: float, mass: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, py: float, theta: float, mass: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, rho: float, phi: float, theta: float, mass: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, pt: float, phi: float, theta: float, mass: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, y: float, eta: float, mass: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, x: float, py: float, eta: float, mass: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, y: float, eta: float, mass: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, px: float, py: float, eta: float, mass: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, rho: float, phi: float, eta: float, mass: float) -> MomentumObject4D: ...
@typing.overload
def obj(*, pt: float, phi: float, eta: float, mass: float) -> MomentumObject4D: ...
