/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef RooExpTurnOnNumerical_H
#define RooExpTurnOnNumerical_H

#include "RooAbsCategory.h"
#include "RooAbsPdf.h"
#include "RooAbsReal.h"
#include "RooCategoryProxy.h"
#include "RooRealProxy.h"

class RooAbsReal;
 
class RooExpTurnOnNumerical : public RooAbsPdf {
public:
  RooExpTurnOnNumerical() {    } ;
  RooExpTurnOnNumerical(const char *name, const char *title, RooAbsReal& _x, RooAbsReal& _mTurnOn, RooAbsReal& _sTurnOn, RooAbsReal & _bCombo);
  RooExpTurnOnNumerical(const RooExpTurnOnNumerical& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooExpTurnOnNumerical(*this,newname); }
  inline virtual ~RooExpTurnOnNumerical() {  }
protected:
  RooRealProxy x ;
  RooRealProxy mO ;
  RooRealProxy sE ;
  RooRealProxy bComb ;
  Double_t evaluate() const ;
private:
  ClassDef(RooExpTurnOnNumerical,1) // RooExpTurnOnNumerical PDF
};
 
#endif
