#!/usr/bin/env python3

import os
import ROOT
import argparse
import utils_noroot as utnr

from logzero import logger as log
#-----------------------------------
class data:
    pdf    = None
    vers   = None
    qsq_dir= None
    cas_dir= None

    l_year = None
    l_trig = None
    l_brem = None

    l_all_trig = ['ETOS', 'GTIS']
    l_all_brem = ['0', '1', '2']
    l_all_year = ['2011', '2012', '2015', '2016', '2017', '2018']
#-----------------------------------
def get_rdf(trig, year):
    data_wc = f'{data.cas_dir}/tools/apply_selection/q2_smear/data/v10.18is/{year}_{trig}/*.root'

    log.debug(f'Loading files in: {data_wc}')
    
    rdf = ROOT.RDataFrame(trig, data_wc)

    rdf.Display().Print()
#-----------------------------------
def get_pdf(trig, year):
    return
#-----------------------------------
def plot(rdf, pdf):
    return
#-----------------------------------
def validate(trig, year):
    rdf = get_rdf(trig, year)
    pdf = get_pdf(trig, year)

    plot(rdf, pdf)
#-----------------------------------
def get_args():
    parser = argparse.ArgumentParser(description='Used to compare smeared MC with fitted data') 
    parser.add_argument('-v', '--vers' , type=str, help='Version of smearing parameters and corresponding fits', required=True)
    parser.add_argument('-y', '--year' , nargs='+', help='Years'        , choices=data.l_all_year, default=data.l_all_year)
    parser.add_argument('-t', '--trig' , nargs='+', help='Triggers'     , choices=data.l_all_trig, default=data.l_all_trig)
    parser.add_argument('-b', '--brem' , nargs='+', help='Brem category', choices=data.l_all_brem, default=data.l_all_brem)
    args = parser.parse_args()

    data.vers   = args.vers
    data.l_year = args.year
    data.l_trig = args.trig
    data.l_brem = args.brem

    data.qsq_dir = get_env_var('QSQSYS')
    data.cas_dir = get_env_var('CASDIR')

    data.plot_dir = utnr.make_dir_path(f'{data.qsq_dir}/validate_smear/{data.vers}')
#-----------------------------------
def get_env_var(varname):
    try:
        value = os.environ[varname]
    except:
        log.error(f'Cannot find {varname} variable in environment')
        raise

    return value
#-----------------------------------
def main():
    for year in data.l_year:
        for trig in data.l_trig:
            validate(trig, year)
#-----------------------------------
if __name__ == '__main__':
    get_args()
    main()
