import typing
from _typeshed import Incomplete
from vector._compute.lorentz import transform4D as transform4D
from vector._compute.planar import x as x, y as y
from vector._compute.spatial import z as z
from vector._methods import AzimuthalRhoPhi as AzimuthalRhoPhi, AzimuthalXY as AzimuthalXY, LongitudinalEta as LongitudinalEta, LongitudinalTheta as LongitudinalTheta, LongitudinalZ as LongitudinalZ, TemporalT as TemporalT, TemporalTau as TemporalTau

def cartesian_t(lib, x1, y1, z1, t1, betax, betay, betaz): ...
def cartesian_tau(lib, x1, y1, z1, tau1, betax, betay, betaz): ...
def cartesian_t_xy_z(lib, x1, y1, z1, t1, x2, y2, z2): ...
def cartesian_tau_xy_z(lib, x1, y1, z1, tau1, x2, y2, z2): ...
def cartesian_t_xy_theta(lib, x1, y1, z1, t1, x2, y2, theta2): ...
def cartesian_tau_xy_theta(lib, x1, y1, z1, tau1, x2, y2, theta2): ...
def cartesian_t_xy_eta(lib, x1, y1, z1, t1, x2, y2, eta2): ...
def cartesian_tau_xy_eta(lib, x1, y1, z1, tau1, x2, y2, eta2): ...
def cartesian_t_rhophi_z(lib, x1, y1, z1, t1, rho2, phi2, z2): ...
def cartesian_tau_rhophi_z(lib, x1, y1, z1, tau1, rho2, phi2, z2): ...
def cartesian_t_rhophi_theta(lib, x1, y1, z1, t1, rho2, phi2, theta2): ...
def cartesian_tau_rhophi_theta(lib, x1, y1, z1, tau1, rho2, phi2, theta2): ...
def cartesian_t_rhophi_eta(lib, x1, y1, z1, t1, rho2, phi2, eta2): ...
def cartesian_tau_rhophi_eta(lib, x1, y1, z1, tau1, rho2, phi2, eta2): ...

dispatch_map: Incomplete

def make_conversion(azimuthal1, longitudinal1, temporal1, azimuthal2, longitudinal2): ...
def dispatch(v1: typing.Any, v2: typing.Any) -> typing.Any: ...
