import typing
from _typeshed import Incomplete
from vector._methods import AzimuthalRhoPhi as AzimuthalRhoPhi, AzimuthalXY as AzimuthalXY, LongitudinalEta as LongitudinalEta, LongitudinalTheta as LongitudinalTheta, LongitudinalZ as LongitudinalZ, TemporalT as TemporalT, TemporalTau as TemporalTau

def xy_z_t(lib, factor, x, y, z, t): ...
def xy_z_tau(lib, factor, x, y, z, tau): ...
def xy_theta_t(lib, factor, x, y, theta, t): ...
def xy_theta_tau(lib, factor, x, y, theta, tau): ...
def xy_eta_t(lib, factor, x, y, eta, t): ...
def xy_eta_tau(lib, factor, x, y, eta, tau): ...
def rhophi_z_t(lib, factor, rho, phi, z, t): ...
def rhophi_z_tau(lib, factor, rho, phi, z, tau): ...
def rhophi_theta_t(lib, factor, rho, phi, theta, t): ...
def rhophi_theta_tau(lib, factor, rho, phi, theta, tau): ...
def rhophi_eta_t(lib, factor, rho, phi, eta, t): ...
def rhophi_eta_tau(lib, factor, rho, phi, eta, tau): ...

dispatch_map: Incomplete

def dispatch(factor: typing.Any, v: typing.Any) -> typing.Any: ...
