import sympy
import typing
import vector
from _typeshed import Incomplete
from vector._methods import Azimuthal as Azimuthal, AzimuthalRhoPhi as AzimuthalRhoPhi, AzimuthalXY as AzimuthalXY, Longitudinal as Longitudinal, LongitudinalEta as LongitudinalEta, LongitudinalTheta as LongitudinalTheta, LongitudinalZ as LongitudinalZ, Lorentz as Lorentz, LorentzMomentum as LorentzMomentum, Planar as Planar, PlanarMomentum as PlanarMomentum, SameVectorType as SameVectorType, Spatial as Spatial, SpatialMomentum as SpatialMomentum, Temporal as Temporal, TemporalT as TemporalT, TemporalTau as TemporalTau, Vector as Vector, Vector2D as Vector2D, Vector3D as Vector3D, Vector4D as Vector4D, VectorProtocol as VectorProtocol

class _lib:
    def where(self, val1: sympy.Expr, val2: sympy.Expr, val3: sympy.Expr) -> sympy.Expr: ...
    def nan_to_num(self, val: sympy.Expr, **kwargs: typing.Any) -> sympy.Expr: ...
    def maximum(self, val1: sympy.Expr | int, val2: sympy.Expr | int) -> sympy.Expr: ...
    def minimum(self, val1: sympy.Expr | int, val2: sympy.Expr | int) -> sympy.Expr: ...
    def arcsin(self, val: sympy.Expr) -> sympy.Expr: ...
    def arccos(self, val: sympy.Expr) -> sympy.Expr: ...
    def arctan(self, val: sympy.Expr) -> sympy.Expr: ...
    def arctan2(self, val1: sympy.Expr, val2: sympy.Expr) -> sympy.Expr: ...
    def arcsinh(self, val: sympy.Expr) -> sympy.Expr: ...
    def arccosh(self, val: sympy.Expr) -> sympy.Expr: ...
    def arctanh(self, val: sympy.Expr) -> sympy.Expr: ...
    def absolute(self, val: sympy.Expr) -> sympy.Expr: ...
    def isclose(self, val1: sympy.Expr, val2: sympy.Expr, *args: float) -> sympy.Equality: ...
    def copysign(self, val1: sympy.Expr, val2: sympy.Expr) -> sympy.Expr: ...
    @property
    def inf(self) -> sympy.Expr: ...
    def sign(self, val: int | float) -> sympy.Expr: ...
    def sqrt(self, val: sympy.Expr) -> sympy.Expr: ...
    def exp(self, val: sympy.Expr) -> sympy.Expr: ...
    def log(self, val: sympy.Expr) -> sympy.Expr: ...
    def sin(self, val: sympy.Expr) -> sympy.Expr: ...
    def cos(self, val: sympy.Expr) -> sympy.Expr: ...
    def tan(self, val: sympy.Expr) -> sympy.Expr: ...
    def sinh(self, val: sympy.Expr) -> sympy.Expr: ...
    def cosh(self, val: sympy.Expr) -> sympy.Expr: ...
    def tanh(self, val: sympy.Expr) -> sympy.Expr: ...
    @property
    def pi(self) -> sympy.Expr: ...

class CoordinatesSympy:
    lib: Incomplete

class AzimuthalSympy(CoordinatesSympy, Azimuthal):
    ObjectClass: type[vector.backends.object.AzimuthalObject]

class LongitudinalSympy(CoordinatesSympy, Longitudinal):
    ObjectClass: type[vector.backends.object.LongitudinalObject]

class TemporalSympy(CoordinatesSympy, Temporal):
    ObjectClass: type[vector.backends.object.TemporalObject]

class AzimuthalSympyXY(AzimuthalSympy, AzimuthalXY):
    x: Incomplete
    y: Incomplete
    def __init__(self, x: sympy.Symbol, y: sympy.Symbol) -> None: ...
    @property
    def elements(self) -> tuple[sympy.Symbol, sympy.Symbol]: ...

class AzimuthalSympyRhoPhi(AzimuthalSympy, AzimuthalRhoPhi):
    rho: Incomplete
    phi: Incomplete
    def __init__(self, rho: sympy.Symbol, phi: sympy.Symbol) -> None: ...
    @property
    def elements(self) -> tuple[sympy.Symbol, sympy.Symbol]: ...

class LongitudinalSympyZ(LongitudinalSympy, LongitudinalZ):
    z: Incomplete
    def __init__(self, z: sympy.Symbol) -> None: ...
    @property
    def elements(self) -> tuple[sympy.Symbol]: ...

class LongitudinalSympyTheta(LongitudinalSympy, LongitudinalTheta):
    theta: Incomplete
    def __init__(self, theta: sympy.Symbol) -> None: ...
    @property
    def elements(self) -> tuple[sympy.Symbol]: ...

class LongitudinalSympyEta(LongitudinalSympy, LongitudinalEta):
    eta: Incomplete
    def __init__(self, eta: sympy.Symbol) -> None: ...
    @property
    def elements(self) -> tuple[sympy.Symbol]: ...

class TemporalSympyT(TemporalSympy, TemporalT):
    t: Incomplete
    def __init__(self, t: sympy.Symbol) -> None: ...
    @property
    def elements(self) -> tuple[sympy.Symbol]: ...

class TemporalSympyTau(TemporalSympy, TemporalTau):
    tau: Incomplete
    def __init__(self, tau: sympy.Symbol) -> None: ...
    @property
    def elements(self) -> tuple[sympy.Symbol]: ...

class VectorSympy(Vector):
    lib: Incomplete
    def __eq__(self, other: typing.Any) -> typing.Any: ...
    def __ne__(self, other: typing.Any) -> typing.Any: ...
    def __abs__(self) -> float: ...
    def __add__(self, other: VectorProtocol) -> VectorProtocol: ...
    def __radd__(self, other: VectorProtocol) -> VectorProtocol: ...
    def __iadd__(self, other: VectorProtocol) -> SameVectorType: ...
    def __sub__(self, other: VectorProtocol) -> VectorProtocol: ...
    def __rsub__(self, other: VectorProtocol) -> VectorProtocol: ...
    def __isub__(self, other: VectorProtocol) -> SameVectorType: ...
    def __mul__(self, other: float) -> VectorProtocol: ...
    def __rmul__(self, other: float) -> VectorProtocol: ...
    def __imul__(self, other: float) -> SameVectorType: ...
    def __neg__(self) -> SameVectorType: ...
    def __pos__(self) -> SameVectorType: ...
    def __truediv__(self, other: float) -> VectorProtocol: ...
    def __rtruediv__(self, other: float) -> VectorProtocol: ...
    def __itruediv__(self, other: float) -> VectorProtocol: ...
    def __pow__(self, other: float) -> float: ...
    def __matmul__(self, other: VectorProtocol) -> float: ...
    def __array_ufunc__(self, ufunc: typing.Any, method: typing.Any, *inputs: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class VectorSympy2D(VectorSympy, Planar, Vector2D):
    azimuthal: AzimuthalSympy
    def __init__(self, azimuthal: AzimuthalSympy | None = None, **kwargs: sympy.Symbol) -> None: ...
    @property
    def x(self) -> sympy.Symbol: ...
    @x.setter
    def x(self, x: sympy.Symbol) -> None: ...
    @property
    def y(self) -> sympy.Symbol: ...
    @y.setter
    def y(self, y: sympy.Symbol) -> None: ...
    @property
    def rho(self) -> sympy.Symbol: ...
    @rho.setter
    def rho(self, rho: sympy.Symbol) -> None: ...
    @property
    def phi(self) -> sympy.Symbol: ...
    @phi.setter
    def phi(self, phi: sympy.Symbol) -> None: ...

class MomentumSympy2D(PlanarMomentum, VectorSympy2D):
    @property
    def px(self) -> sympy.Symbol: ...
    azimuthal: Incomplete
    @px.setter
    def px(self, px: sympy.Symbol) -> None: ...
    @property
    def py(self) -> sympy.Symbol: ...
    @py.setter
    def py(self, py: sympy.Symbol) -> None: ...
    @property
    def pt(self) -> sympy.Symbol: ...
    @pt.setter
    def pt(self, pt: sympy.Symbol) -> None: ...

class VectorSympy3D(VectorSympy, Spatial, Vector3D):
    azimuthal: AzimuthalSympy
    longitudinal: LongitudinalSympy
    def __init__(self, azimuthal: AzimuthalSympy | None = None, longitudinal: LongitudinalSympy | None = None, **kwargs: sympy.Symbol) -> None: ...
    @property
    def x(self) -> sympy.Symbol: ...
    @x.setter
    def x(self, x: sympy.Symbol) -> None: ...
    @property
    def y(self) -> sympy.Symbol: ...
    @y.setter
    def y(self, y: sympy.Symbol) -> None: ...
    @property
    def rho(self) -> sympy.Symbol: ...
    @rho.setter
    def rho(self, rho: sympy.Symbol) -> None: ...
    @property
    def phi(self) -> sympy.Symbol: ...
    @phi.setter
    def phi(self, phi: sympy.Symbol) -> None: ...
    @property
    def z(self) -> sympy.Symbol: ...
    @z.setter
    def z(self, z: sympy.Symbol) -> None: ...
    @property
    def theta(self) -> sympy.Symbol: ...
    @theta.setter
    def theta(self, theta: sympy.Symbol) -> None: ...
    @property
    def eta(self) -> sympy.Symbol: ...
    @eta.setter
    def eta(self, eta: sympy.Symbol) -> None: ...

class MomentumSympy3D(SpatialMomentum, VectorSympy3D):
    @property
    def px(self) -> sympy.Symbol: ...
    azimuthal: Incomplete
    @px.setter
    def px(self, px: sympy.Symbol) -> None: ...
    @property
    def py(self) -> sympy.Symbol: ...
    @py.setter
    def py(self, py: sympy.Symbol) -> None: ...
    @property
    def pt(self) -> sympy.Symbol: ...
    @pt.setter
    def pt(self, pt: sympy.Symbol) -> None: ...
    @property
    def pz(self) -> sympy.Symbol: ...
    longitudinal: Incomplete
    @pz.setter
    def pz(self, pz: sympy.Symbol) -> None: ...

class VectorSympy4D(VectorSympy, Lorentz, Vector4D):
    azimuthal: AzimuthalSympy
    longitudinal: LongitudinalSympy
    temporal: TemporalSympy
    def __init__(self, azimuthal: AzimuthalSympy | None = None, longitudinal: LongitudinalSympy | None = None, temporal: TemporalSympy | None = None, **kwargs: sympy.Symbol) -> None: ...
    @property
    def x(self) -> sympy.Symbol: ...
    @x.setter
    def x(self, x: sympy.Symbol) -> None: ...
    @property
    def y(self) -> sympy.Symbol: ...
    @y.setter
    def y(self, y: sympy.Symbol) -> None: ...
    @property
    def rho(self) -> sympy.Symbol: ...
    @rho.setter
    def rho(self, rho: sympy.Symbol) -> None: ...
    @property
    def phi(self) -> sympy.Symbol: ...
    @phi.setter
    def phi(self, phi: sympy.Symbol) -> None: ...
    @property
    def z(self) -> sympy.Symbol: ...
    @z.setter
    def z(self, z: sympy.Symbol) -> None: ...
    @property
    def theta(self) -> sympy.Symbol: ...
    @theta.setter
    def theta(self, theta: sympy.Symbol) -> None: ...
    @property
    def eta(self) -> sympy.Symbol: ...
    @eta.setter
    def eta(self, eta: sympy.Symbol) -> None: ...
    @property
    def t(self) -> sympy.Symbol: ...
    @t.setter
    def t(self, t: sympy.Symbol) -> None: ...
    @property
    def tau(self) -> sympy.Symbol: ...
    @tau.setter
    def tau(self, tau: sympy.Symbol) -> None: ...

class MomentumSympy4D(LorentzMomentum, VectorSympy4D):
    @property
    def px(self) -> sympy.Symbol: ...
    azimuthal: Incomplete
    @px.setter
    def px(self, px: sympy.Symbol) -> None: ...
    @property
    def py(self) -> sympy.Symbol: ...
    @py.setter
    def py(self, py: sympy.Symbol) -> None: ...
    @property
    def pt(self) -> sympy.Symbol: ...
    @pt.setter
    def pt(self, pt: sympy.Symbol) -> None: ...
    @property
    def pz(self) -> sympy.Symbol: ...
    longitudinal: Incomplete
    @pz.setter
    def pz(self, pz: sympy.Symbol) -> None: ...
    @property
    def E(self) -> sympy.Symbol: ...
    temporal: Incomplete
    @E.setter
    def E(self, E: sympy.Symbol) -> None: ...
    @property
    def e(self) -> sympy.Symbol: ...
    @e.setter
    def e(self, e: sympy.Symbol) -> None: ...
    @property
    def energy(self) -> sympy.Symbol: ...
    @energy.setter
    def energy(self, energy: sympy.Symbol) -> None: ...
    @property
    def M(self) -> sympy.Symbol: ...
    @M.setter
    def M(self, M: sympy.Symbol) -> None: ...
    @property
    def m(self) -> sympy.Symbol: ...
    @m.setter
    def m(self, m: sympy.Symbol) -> None: ...
    @property
    def mass(self) -> sympy.Symbol: ...
    @mass.setter
    def mass(self, mass: sympy.Symbol) -> None: ...
