#!/bin/bash

#-------------------------------------------------------------------
display_help()
{
    echo "Script used to send jobs to do q2 calibration fits"
    echo ""
    echo "-k: Kind of job, q2sys or q2nom"
    echo "-v: Version of the output"
    echo "-d: Flag specifying simulation 0 or data 1"
    echo "-r: Real run (1) or test run (0 default) "
    echo "-t: Trigger"
    echo "-y: Year or dataset"
    echo "-b: Bremsstrahlung category"
}
#-------------------------------------------------------------------
get_args()
{
    REAL=0
    TRIG='all'
    YEAR='all'
    BREM='all'
    while getopts :hf:k:v:d:r:t:y:b: option
    do
	case "${option}"
	    in
	    k)KIND=${OPTARG};;
	    v)VERS=${OPTARG};;
	    d)DATA=${OPTARG};;
	    r)REAL=${OPTARG};;
	    #---------------
	    t)TRIG=${OPTARG};;
	    y)YEAR=${OPTARG};;
	    b)BREM=${OPTARG};;
	    #---------------
            h)  
                display_help
                exit 0
                ;;  
           \?)  echo "Invalid option: -${OPTARG}"
                display_help
                exit 1
                ;;  
            :)  echo "$0: Arguments needed"
                display_help
                exit 1
                ;; 
	esac
    done

    IFS=',' read -ra TRIG <<< "$TRIG"
    IFS=',' read -ra YEAR <<< "$YEAR"
    IFS=',' read -ra BREM <<< "$BREM"
}
#-------------------------------------------------------------------
prepare()
{
    print_q2_settings -i 0 -t $TRIG -d $YEAR -b $BREM > .settings.log

    NJOB=$(cat .settings.log | grep NJOB | awk -F '=' '{print$2}')
    JOBDIR=/publicfs/ucas/user/campoverde/Jobs/$KIND
    DATE=$(date | sed "s|\s|_|g" | sed "s|:|_|g")
    JOBDIR=$JOBDIR"_"$DATE

    mkdir -p $JOBDIR
    cd $JOBDIR

    OFILE=$KIND_%{ClusterId}_%{ProcId}
    MEMORY=4000

    echo "NJOB=$NJOB"
    echo "JOBDIR=$JOBDIR"
}
#-------------------------------------------------------------------
submit()
{
    if   [[ $REAL -eq 0 ]];then
	echo "This is a test, not submitting job"
    elif [[ "$KIND" == "q2sys" ]];then
	SYST=$THIRD
	SUBMIT=$(which submit_q2sys)
	hep_sub -n $NJOB -g lhcb -e $OFILE".err" -o $OFILE".out" -argu %{ProcId} $VERS $SYST -mem $MEMORY $SUBMIT 
    elif [[ "$KIND" == "q2mom" ]];then
	ISSM=$THIRD
	SUBMIT=$(which submit_q2mom)
	hep_sub -n $NJOB -g lhcb -e $OFILE".err" -o $OFILE".out" -argu %{ProcId} $VERS $ISSM -mem $MEMORY $SUBMIT 
    else
	echo "Invalid job type: $KIND"
	kill -INT $$
    fi
}
#-------------------------------------------------------------------
get_args $@
prepare
submit

