#!/bin/bash

#-------------------------------------------------------------------
display_help()
{
    echo "Script used to send jobs to do q2 calibration fits"
    echo ""
    echo "-k: Kind of job, q2sys or q2nom"
    echo "-v: Version of the output"
    echo "-t: Flag specifying simulation 0 or data 1"
    echo "-r: Real run (1) or test run (0 default) "
}
#-------------------------------------------------------------------
get_args()
{
    REAL=0
    while getopts :hf:k:v:t:r: option
    do
	case "${option}"
	    in
	    k)KIND=${OPTARG};;
	    v)VERS=${OPTARG};;
	    d)DATA=${OPTARG};;
	    r)REAL=${OPTARG};;
            h)  
                display_help
                exit 0
                ;;  
           \?)  echo "Invalid option: -${OPTARG}"
                display_help
                exit 1
                ;;  
            :)  echo "$0: Arguments needed"
                display_help
                exit 1
                ;; 
	esac
    done
}
#-------------------------------------------------------------------
prepare()
{
    source $HOME/.bashrc
    conda_init
    conda activate q2_syst 
    print_q2_settings -i 0 -d > .settings.log

    NJOB=$(cat .settings.log | grep NJOB | awk -F '=' '{print$2}')
    JOBDIR=/publicfs/ucas/user/campoverde/Jobs/$KIND
    DATE=$(date | sed "s|\s|_|g" | sed "s|:|_|g")
    JOBDIR=$JOBDIR"_"$DATE

    mkdir -p $JOBDIR
    cd $JOBDIR

    OFILE=$KIND_%{ClusterId}_%{ProcId}
    MEMORY=4000

    if [[ $REAL -ne 1 ]];then
	NJOB=1
    fi
    
    echo "NJOB=$NJOB"
    echo "JOBDIR=$JOBDIR"
}
#-------------------------------------------------------------------
submit()
{
    if   [[ "$KIND" == "q2sys" ]];then
	SYST=$THIRD
	SUBMIT=$(which submit_q2sys)
	hep_sub -n $NJOB -g lhcb -e $OFILE".err" -o $OFILE".out" -argu %{ProcId} $VERS $SYST -mem $MEMORY $SUBMIT 
    elif [[ "$KIND" == "q2mom" ]];then
	ISSM=$THIRD
	SUBMIT=$(which submit_q2mom)
	hep_sub -n $NJOB -g lhcb -e $OFILE".err" -o $OFILE".out" -argu %{ProcId} $VERS $ISSM -mem $MEMORY $SUBMIT 
    else
	echo "Invalid job type: $KIND"
	kill -INT $$
    fi
}
#-------------------------------------------------------------------
get_args $@
prepare
submit

