#!/bin/bash

#-------------------------------------------------------------------
get_args()
{
    while getopts k:v:t: option
    do
	case "${option}"
	    in
	    k)KIND=${OPTARG};;
	    v)VERS=${OPTARG};;
	    t)THIRD=${OPTARG};;
	esac
    done
}
#-------------------------------------------------------------------
prepare()
{
    source $HOME/.bashrc
    conda_init
    conda activate q2_syst 
    print_q2_settings -i 0 -d > .settings.log

    NJOB=$(cat .settings.log | grep NJOB | awk -F '=' '{print$2}')
    JOBDIR=/publicfs/ucas/user/campoverde/Jobs/$KIND
    DATE=$(date | sed "s|\s|_|g" | sed "s|:|_|g")
    JOBDIR=$JOBDIR"_"$DATE

    mkdir -p $JOBDIR
    CDIR=$(pwd -P)
    cd $JOBDIR
    
    OFILE=$KIND_%{ClusterId}_%{ProcId}
    MEMORY=4000
    
    echo "NJOB=$NJOB"
}
#-------------------------------------------------------------------
submit()
{
    if   [[ "$KIND" == "q2sys" ]];then
	SYST=$THIRD
	SUBMIT=$(which submit_q2sys)
	hep_sub -n $NJOB -g lhcb -e $OFILE".err" -o $OFILE".out" -argu %{ProcId} $VERS $SYST -mem $MEMORY $SUBMIT 
    elif [[ "$KIND" == "q2mom" ]];then
	ISSM=$THIRD
	SUBMIT=$(which submit_q2mom)
	hep_sub -n $NJOB -g lhcb -e $OFILE".err" -o $OFILE".out" -argu %{ProcId} $VERS $ISSM -mem $MEMORY $SUBMIT 
    else
	echo "Invalid job type: $KIND"
	kill -INT $$
    fi
}
#-------------------------------------------------------------------
get_args $@
prepare
submit

