#!/bin/bash

source $HOME/.bashrc
conda_init
conda activate q2_syst 

IJOB=$1
VERS=$2
ISSM=$3
CACHE_NAME=settings_$IJOB.txt

print_q2_settings -d -i $IJOB > $CACHE_NAME 

DSET=$(cat $CACHE_NAME | grep YEAR | awk -F '=' '{print$2}')
TRIG=$(cat $CACHE_NAME | grep TRIG | awk -F '=' '{print$2}')
BREM=$(cat $CACHE_NAME | grep BREM | awk -F '=' '{print$2}')

echo "$DSET, $TRIG, $BREM, $VERS, $ISSM"

if [[ $ISSM -eq 1 ]];then
    echo "Doing simulation"
    get_q2_resolutions -d $DSET -t $TRIG -b $BREM -v $VERS -s
else
    echo "Doing data"
    get_q2_resolutions -d $DSET -t $TRIG -b $BREM -v $VERS
fi

