import typing
from _typeshed import Incomplete
from vector._compute.planar import x as x, y as y
from vector._compute.spatial import eta as eta, z as z
from vector._methods import AzimuthalRhoPhi as AzimuthalRhoPhi, AzimuthalXY as AzimuthalXY, LongitudinalEta as LongitudinalEta, LongitudinalTheta as LongitudinalTheta, LongitudinalZ as LongitudinalZ

def xy_z_xy_z(lib, rtol, atol, equal_nan, x1, y1, z1, x2, y2, z2): ...
def xy_z_xy_theta(lib, rtol, atol, equal_nan, x1, y1, z1, x2, y2, theta2): ...
def xy_z_xy_eta(lib, rtol, atol, equal_nan, x1, y1, z1, x2, y2, eta2): ...
def xy_z_rhophi_z(lib, rtol, atol, equal_nan, x1, y1, z1, rho2, phi2, z2): ...
def xy_z_rhophi_theta(lib, rtol, atol, equal_nan, x1, y1, z1, rho2, phi2, theta2): ...
def xy_z_rhophi_eta(lib, rtol, atol, equal_nan, x1, y1, z1, rho2, phi2, eta2): ...
def xy_theta_xy_z(lib, rtol, atol, equal_nan, x1, y1, theta1, x2, y2, z2): ...
def xy_theta_xy_theta(lib, rtol, atol, equal_nan, x1, y1, theta1, x2, y2, theta2): ...
def xy_theta_xy_eta(lib, rtol, atol, equal_nan, x1, y1, theta1, x2, y2, eta2): ...
def xy_theta_rhophi_z(lib, rtol, atol, equal_nan, x1, y1, theta1, rho2, phi2, z2): ...
def xy_theta_rhophi_theta(lib, rtol, atol, equal_nan, x1, y1, theta1, rho2, phi2, theta2): ...
def xy_theta_rhophi_eta(lib, rtol, atol, equal_nan, x1, y1, theta1, rho2, phi2, eta2): ...
def xy_eta_xy_z(lib, rtol, atol, equal_nan, x1, y1, eta1, x2, y2, z2): ...
def xy_eta_xy_theta(lib, rtol, atol, equal_nan, x1, y1, eta1, x2, y2, theta2): ...
def xy_eta_xy_eta(lib, rtol, atol, equal_nan, x1, y1, eta1, x2, y2, eta2): ...
def xy_eta_rhophi_z(lib, rtol, atol, equal_nan, x1, y1, eta1, rho2, phi2, z2): ...
def xy_eta_rhophi_theta(lib, rtol, atol, equal_nan, x1, y1, eta1, rho2, phi2, theta2): ...
def xy_eta_rhophi_eta(lib, rtol, atol, equal_nan, x1, y1, eta1, rho2, phi2, eta2): ...
def rhophi_z_xy_z(lib, rtol, atol, equal_nan, rho1, phi1, z1, x2, y2, z2): ...
def rhophi_z_xy_theta(lib, rtol, atol, equal_nan, rho1, phi1, z1, x2, y2, theta2): ...
def rhophi_z_xy_eta(lib, rtol, atol, equal_nan, rho1, phi1, z1, x2, y2, eta2): ...
def rhophi_z_rhophi_z(lib, rtol, atol, equal_nan, rho1, phi1, z1, rho2, phi2, z2): ...
def rhophi_z_rhophi_theta(lib, rtol, atol, equal_nan, rho1, phi1, z1, rho2, phi2, theta2): ...
def rhophi_z_rhophi_eta(lib, rtol, atol, equal_nan, rho1, phi1, z1, rho2, phi2, eta2): ...
def rhophi_theta_xy_z(lib, rtol, atol, equal_nan, rho1, phi1, theta1, x2, y2, z2): ...
def rhophi_theta_xy_theta(lib, rtol, atol, equal_nan, rho1, phi1, theta1, x2, y2, theta2): ...
def rhophi_theta_xy_eta(lib, rtol, atol, equal_nan, rho1, phi1, theta1, x2, y2, eta2): ...
def rhophi_theta_rhophi_z(lib, rtol, atol, equal_nan, rho1, phi1, theta1, rho2, phi2, z2): ...
def rhophi_theta_rhophi_theta(lib, rtol, atol, equal_nan, rho1, phi1, theta1, rho2, phi2, theta2): ...
def rhophi_theta_rhophi_eta(lib, rtol, atol, equal_nan, rho1, phi1, theta1, rho2, phi2, eta2): ...
def rhophi_eta_xy_z(lib, rtol, atol, equal_nan, rho1, phi1, eta1, x2, y2, z2): ...
def rhophi_eta_xy_theta(lib, rtol, atol, equal_nan, rho1, phi1, eta1, x2, y2, theta2): ...
def rhophi_eta_xy_eta(lib, rtol, atol, equal_nan, rho1, phi1, eta1, x2, y2, eta2): ...
def rhophi_eta_rhophi_z(lib, rtol, atol, equal_nan, rho1, phi1, eta1, rho2, phi2, z2): ...
def rhophi_eta_rhophi_theta(lib, rtol, atol, equal_nan, rho1, phi1, eta1, rho2, phi2, theta2): ...
def rhophi_eta_rhophi_eta(lib, rtol, atol, equal_nan, rho1, phi1, eta1, rho2, phi2, eta2): ...

dispatch_map: Incomplete

def dispatch(rtol: typing.Any, atol: typing.Any, equal_nan: typing.Any, v1: typing.Any, v2: typing.Any) -> typing.Any: ...
