import typing
from _typeshed import Incomplete
from vector._compute.planar import x as x, y as y
from vector._compute.spatial import z as z
from vector._methods import AzimuthalRhoPhi as AzimuthalRhoPhi, AzimuthalXY as AzimuthalXY, LongitudinalEta as LongitudinalEta, LongitudinalTheta as LongitudinalTheta, LongitudinalZ as LongitudinalZ

def cartesian_xzx(lib, phi, theta, psi, x, y, z): ...
def cartesian_xyx(lib, phi, theta, psi, x, y, z): ...
def cartesian_yxy(lib, phi, theta, psi, x, y, z): ...
def cartesian_yzy(lib, phi, theta, psi, x, y, z): ...
def cartesian_zyz(lib, phi, theta, psi, x, y, z): ...
def cartesian_zxz(lib, phi, theta, psi, x, y, z): ...
def cartesian_xzy(lib, phi, theta, psi, x, y, z): ...
def cartesian_xyz(lib, phi, theta, psi, x, y, z): ...
def cartesian_yxz(lib, phi, theta, psi, x, y, z): ...
def cartesian_yzx(lib, phi, theta, psi, x, y, z): ...
def cartesian_zyx(lib, phi, theta, psi, x, y, z): ...
def cartesian_zxy(lib, phi, theta, psi, x, y, z): ...

dispatch_map: Incomplete

def make_conversion(azimuthal, longitudinal, order): ...
def dispatch(phi: typing.Any, theta: typing.Any, psi: typing.Any, order: typing.Any, v: typing.Any) -> typing.Any: ...
