import typing
from _typeshed import Incomplete
from vector._methods import AzimuthalRhoPhi as AzimuthalRhoPhi, AzimuthalXY as AzimuthalXY, LongitudinalEta as LongitudinalEta, LongitudinalTheta as LongitudinalTheta, LongitudinalZ as LongitudinalZ

def rectify(lib, phi): ...
def xy_z(lib, factor, x, y, z): ...
def xy_theta(lib, factor, x, y, theta): ...
def xy_eta(lib, factor, x, y, eta): ...
def rhophi_z(lib, factor, rho, phi, z): ...
def rhophi_theta(lib, factor, rho, phi, theta): ...
def rhophi_eta(lib, factor, rho, phi, eta): ...

dispatch_map: Incomplete

def dispatch(factor: typing.Any, v: typing.Any) -> typing.Any: ...
