import typing
from _typeshed import Incomplete
from vector._compute.planar import x as x, y as y
from vector._compute.spatial import z as z
from vector._methods import AzimuthalRhoPhi as AzimuthalRhoPhi, AzimuthalXY as AzimuthalXY, LongitudinalEta as LongitudinalEta, LongitudinalTheta as LongitudinalTheta, LongitudinalZ as LongitudinalZ

def xy_z(lib, angle, x, y, z): ...
def xy_theta(lib, angle, x, y, theta): ...
def xy_eta(lib, angle, x, y, eta): ...
def rhophi_z(lib, angle, rho, phi, z): ...
def rhophi_theta(lib, angle, rho, phi, theta): ...
def rhophi_eta(lib, angle, rho, phi, eta): ...

dispatch_map: Incomplete

def dispatch(angle: typing.Any, v: typing.Any) -> typing.Any: ...
