import typing
from _typeshed import Incomplete
from vector._compute.planar import x as x, y as y
from vector._compute.spatial import z as z
from vector._methods import AzimuthalRhoPhi as AzimuthalRhoPhi, AzimuthalXY as AzimuthalXY, LongitudinalEta as LongitudinalEta, LongitudinalTheta as LongitudinalTheta, LongitudinalZ as LongitudinalZ

def cartesian(lib, xx, xy, xz, yx, yy, yz, zx, zy, zz, x, y, z): ...
def xy_theta(lib, xx, xy, xz, yx, yy, yz, zx, zy, zz, x, y, theta): ...
def xy_eta(lib, xx, xy, xz, yx, yy, yz, zx, zy, zz, x, y, eta): ...
def rhophi_z(lib, xx, xy, xz, yx, yy, yz, zx, zy, zz, rho, phi, z): ...
def rhophi_theta(lib, xx, xy, xz, yx, yy, yz, zx, zy, zz, rho, phi, theta): ...
def rhophi_eta(lib, xx, xy, xz, yx, yy, yz, zx, zy, zz, rho, phi, eta): ...

dispatch_map: Incomplete

def dispatch(obj: typing.Any, v: typing.Any) -> typing.Any: ...
