import typing
from _typeshed import Incomplete
from vector._compute.planar import rho as rho
from vector._methods import AzimuthalRhoPhi as AzimuthalRhoPhi, AzimuthalXY as AzimuthalXY, LongitudinalEta as LongitudinalEta, LongitudinalTheta as LongitudinalTheta, LongitudinalZ as LongitudinalZ

def xy_z(lib, x, y, z): ...
def xy_theta(lib, x, y, theta): ...
def xy_eta(lib, x, y, eta): ...
def rhophi_z(lib, rho, phi, z): ...
def rhophi_theta(lib, rho, phi, theta): ...
def rhophi_eta(lib, rho, phi, eta): ...

dispatch_map: Incomplete

def dispatch(v: typing.Any) -> typing.Any: ...
