args:
  # ------------
  # mm
  # ------------
  - { block : -1, group : test_003, fit_cfg : rare/rk/mm   , q2bin :     low, mva_cmb : 50, mva_prc : 50} 
  - { block : -1, group : test_003, fit_cfg : rare/rk/mm   , q2bin : central, mva_cmb : 50, mva_prc : 50} 
  - { block : -1, group : test_003, fit_cfg : rare/rk/mm   , q2bin :    high, mva_cmb : 50, mva_prc : 50} 
  # ------------                                                                                          
  - { block : -1, group : test_003, fit_cfg : rare/rkst/mm , q2bin :     low, mva_cmb : 50, mva_prc : 50} 
  - { block : -1, group : test_003, fit_cfg : rare/rkst/mm , q2bin : central, mva_cmb : 50, mva_prc : 50} 
  - { block : -1, group : test_003, fit_cfg : rare/rkst/mm , q2bin :    high, mva_cmb : 50, mva_prc : 50} 
  # ------------
  # ee 
  # ------------
  - { block : -1, group : test_003, fit_cfg : rare/rk/ee   , q2bin :     low, mva_cmb : 50, mva_prc : 50} 
  - { block : -1, group : test_003, fit_cfg : rare/rk/ee   , q2bin : central, mva_cmb : 50, mva_prc : 50} 
  - { block : -1, group : test_003, fit_cfg : rare/rk/ee   , q2bin :    high, mva_cmb : 50, mva_prc : 50} 
  # ------------
  - { block : -1, group : test_003, fit_cfg : rare/rkst/ee , q2bin :     low, mva_cmb : 50, mva_prc : 50} 
  - { block : -1, group : test_003, fit_cfg : rare/rkst/ee , q2bin : central, mva_cmb : 50, mva_prc : 50} 
  - { block : -1, group : test_003, fit_cfg : rare/rkst/ee , q2bin :    high, mva_cmb : 50, mva_prc : 50} 
outputs:
  - data.json
  - fit_linear.png
  - fit_log.png
  - fit.pkl
  - parameters.json
  - parameters.yaml
  - post_fit.tex
  - post_fit.txt
  - selection.yaml
