import typing
import vector
from vector._typeutils import BoolCollection as BoolCollection, FloatArray as FloatArray, ScalarCollection as ScalarCollection, TransformProtocol2D as TransformProtocol2D, TransformProtocol3D as TransformProtocol3D, TransformProtocol4D as TransformProtocol4D

Module = typing.Any

class Coordinates: ...

class Azimuthal(Coordinates):
    @property
    def elements(self) -> tuple[ScalarCollection, ScalarCollection]: ...

class Longitudinal(Coordinates):
    @property
    def elements(self) -> tuple[ScalarCollection]: ...

class Temporal(Coordinates):
    @property
    def elements(self) -> tuple[ScalarCollection]: ...

class AzimuthalXY(Azimuthal):
    x: ScalarCollection
    y: ScalarCollection

class AzimuthalRhoPhi(Azimuthal):
    rho: ScalarCollection
    phi: ScalarCollection

class LongitudinalZ(Longitudinal):
    z: ScalarCollection

class LongitudinalTheta(Longitudinal):
    theta: ScalarCollection

class LongitudinalEta(Longitudinal):
    eta: ScalarCollection

class TemporalT(Temporal):
    t: ScalarCollection

class TemporalTau(Temporal):
    tau: ScalarCollection
SameVectorType = typing.TypeVar('SameVectorType', bound='VectorProtocol')

class VectorProtocol:
    def __add__(self, other: VectorProtocol) -> VectorProtocol: ...
    @property
    def lib(self) -> Module: ...
    ProjectionClass2D: type[VectorProtocolPlanar]
    ProjectionClass3D: type[VectorProtocolSpatial]
    ProjectionClass4D: type[VectorProtocolLorentz]
    GenericClass: type[VectorProtocol]
    MomentumClass: type[VectorProtocol]
    def to_Vector2D(self) -> VectorProtocolPlanar: ...
    def to_Vector3D(self) -> VectorProtocolSpatial: ...
    def to_Vector4D(self) -> VectorProtocolLorentz: ...
    def to_2D(self) -> VectorProtocolPlanar: ...
    def to_3D(self) -> VectorProtocolSpatial: ...
    def to_4D(self) -> VectorProtocolLorentz: ...
    def to_xy(self) -> VectorProtocolPlanar: ...
    def to_pxpy(self) -> VectorProtocolPlanar: ...
    def to_rhophi(self) -> VectorProtocolPlanar: ...
    def to_ptphi(self) -> VectorProtocolPlanar: ...
    def to_xyz(self) -> VectorProtocolSpatial: ...
    def to_xytheta(self) -> VectorProtocolSpatial: ...
    def to_xyeta(self) -> VectorProtocolSpatial: ...
    def to_pxpypz(self) -> VectorProtocolSpatial: ...
    def to_pxpytheta(self) -> VectorProtocolSpatial: ...
    def to_pxpyeta(self) -> VectorProtocolSpatial: ...
    def to_rhophiz(self) -> VectorProtocolSpatial: ...
    def to_rhophitheta(self) -> VectorProtocolSpatial: ...
    def to_rhophieta(self) -> VectorProtocolSpatial: ...
    def to_ptphipz(self) -> VectorProtocolSpatial: ...
    def to_ptphitheta(self) -> VectorProtocolSpatial: ...
    def to_ptphieta(self) -> VectorProtocolSpatial: ...
    def to_xyzt(self) -> VectorProtocolLorentz: ...
    def to_xyztau(self) -> VectorProtocolLorentz: ...
    def to_xythetat(self) -> VectorProtocolLorentz: ...
    def to_xythetatau(self) -> VectorProtocolLorentz: ...
    def to_xyetat(self) -> VectorProtocolLorentz: ...
    def to_xyetatau(self) -> VectorProtocolLorentz: ...
    def to_pxpypzenergy(self) -> VectorProtocolLorentz: ...
    def to_pxpythetaenergy(self) -> VectorProtocolLorentz: ...
    def to_pxpyetaenergy(self) -> VectorProtocolLorentz: ...
    def to_pxpypzmass(self) -> VectorProtocolLorentz: ...
    def to_pxpythetamass(self) -> VectorProtocolLorentz: ...
    def to_pxpyetamass(self) -> VectorProtocolLorentz: ...
    def to_rhophizt(self) -> VectorProtocolLorentz: ...
    def to_rhophiztau(self) -> VectorProtocolLorentz: ...
    def to_rhophithetat(self) -> VectorProtocolLorentz: ...
    def to_rhophithetatau(self) -> VectorProtocolLorentz: ...
    def to_rhophietat(self) -> VectorProtocolLorentz: ...
    def to_rhophietatau(self) -> VectorProtocolLorentz: ...
    def to_ptphipzenergy(self) -> VectorProtocolLorentz: ...
    def to_ptphithetaenergy(self) -> VectorProtocolLorentz: ...
    def to_ptphietaenergy(self) -> VectorProtocolLorentz: ...
    def to_ptphipzmass(self) -> VectorProtocolLorentz: ...
    def to_ptphithetamass(self) -> VectorProtocolLorentz: ...
    def to_ptphietamass(self) -> VectorProtocolLorentz: ...
    def unit(self) -> SameVectorType: ...
    def dot(self, other: VectorProtocol) -> ScalarCollection: ...
    def add(self, other: VectorProtocol) -> VectorProtocol: ...
    def subtract(self, other: VectorProtocol) -> VectorProtocol: ...
    def scale(self, factor: ScalarCollection) -> SameVectorType: ...
    def equal(self, other: VectorProtocol) -> BoolCollection: ...
    def not_equal(self, other: VectorProtocol) -> BoolCollection: ...
    def isclose(self, other: VectorProtocol, rtol: ScalarCollection = 1e-05, atol: ScalarCollection = 1e-08, equal_nan: BoolCollection = False) -> BoolCollection: ...
    def like(self, other: VectorProtocol) -> VectorProtocol: ...

class VectorProtocolPlanar(VectorProtocol):
    @property
    def azimuthal(self) -> Azimuthal: ...
    @property
    def x(self) -> ScalarCollection: ...
    @property
    def y(self) -> ScalarCollection: ...
    @property
    def rho(self) -> ScalarCollection: ...
    @property
    def rho2(self) -> ScalarCollection: ...
    @property
    def phi(self) -> ScalarCollection: ...
    def scale2D(self, factor: ScalarCollection) -> SameVectorType: ...
    @property
    def neg2D(self) -> SameVectorType: ...
    def deltaphi(self, other: VectorProtocol) -> ScalarCollection: ...
    def rotateZ(self, angle: ScalarCollection) -> SameVectorType: ...
    def transform2D(self, obj: TransformProtocol2D) -> SameVectorType: ...
    def is_parallel(self, other: VectorProtocol, tolerance: ScalarCollection = 1e-05) -> BoolCollection: ...
    def is_antiparallel(self, other: VectorProtocol, tolerance: ScalarCollection = 1e-05) -> BoolCollection: ...
    def is_perpendicular(self, other: VectorProtocol, tolerance: ScalarCollection = 1e-05) -> BoolCollection: ...

class VectorProtocolSpatial(VectorProtocolPlanar):
    @property
    def longitudinal(self) -> Longitudinal: ...
    @property
    def z(self) -> ScalarCollection: ...
    @property
    def theta(self) -> ScalarCollection: ...
    @property
    def eta(self) -> ScalarCollection: ...
    @property
    def costheta(self) -> ScalarCollection: ...
    @property
    def cottheta(self) -> ScalarCollection: ...
    @property
    def mag(self) -> ScalarCollection: ...
    @property
    def mag2(self) -> ScalarCollection: ...
    def scale3D(self, factor: ScalarCollection) -> SameVectorType: ...
    @property
    def neg3D(self) -> SameVectorType: ...
    def cross(self, other: VectorProtocolSpatial) -> VectorProtocolSpatial: ...
    def deltaangle(self, other: VectorProtocolSpatial | VectorProtocolLorentz) -> ScalarCollection: ...
    def deltaeta(self, other: VectorProtocolSpatial | VectorProtocolLorentz) -> ScalarCollection: ...
    def deltaR(self, other: VectorProtocolSpatial | VectorProtocolLorentz) -> ScalarCollection: ...
    def deltaR2(self, other: VectorProtocolSpatial | VectorProtocolLorentz) -> ScalarCollection: ...
    def rotateX(self, angle: ScalarCollection) -> SameVectorType: ...
    def rotateY(self, angle: ScalarCollection) -> SameVectorType: ...
    def rotate_axis(self, axis: VectorProtocolSpatial, angle: ScalarCollection) -> SameVectorType: ...
    def rotate_euler(self, phi: ScalarCollection, theta: ScalarCollection, psi: ScalarCollection, order: str = 'zxz') -> SameVectorType: ...
    def rotate_nautical(self, yaw: ScalarCollection, pitch: ScalarCollection, roll: ScalarCollection) -> SameVectorType: ...
    def rotate_quaternion(self, u: ScalarCollection, i: ScalarCollection, j: ScalarCollection, k: ScalarCollection) -> SameVectorType: ...
    def transform3D(self, obj: TransformProtocol3D) -> SameVectorType: ...
    def is_parallel(self, other: VectorProtocol, tolerance: ScalarCollection = 1e-05) -> BoolCollection: ...
    def is_antiparallel(self, other: VectorProtocol, tolerance: ScalarCollection = 1e-05) -> BoolCollection: ...
    def is_perpendicular(self, other: VectorProtocol, tolerance: ScalarCollection = 1e-05) -> BoolCollection: ...

class VectorProtocolLorentz(VectorProtocolSpatial):
    @property
    def temporal(self) -> Temporal: ...
    @property
    def t(self) -> ScalarCollection: ...
    @property
    def t2(self) -> ScalarCollection: ...
    @property
    def tau(self) -> ScalarCollection: ...
    @property
    def tau2(self) -> ScalarCollection: ...
    @property
    def beta(self) -> ScalarCollection: ...
    @property
    def gamma(self) -> ScalarCollection: ...
    @property
    def rapidity(self) -> ScalarCollection: ...
    def deltaRapidityPhi(self, other: VectorProtocolLorentz) -> ScalarCollection: ...
    def deltaRapidityPhi2(self, other: VectorProtocolLorentz) -> ScalarCollection: ...
    def scale4D(self, factor: ScalarCollection) -> SameVectorType: ...
    @property
    def neg4D(self) -> SameVectorType: ...
    def boost_p4(self, p4: VectorProtocolLorentz) -> SameVectorType: ...
    def boost_beta3(self, beta3: VectorProtocolSpatial) -> SameVectorType: ...
    def boost(self, booster: VectorProtocolSpatial | VectorProtocolLorentz) -> SameVectorType: ...
    def boostCM_of_p4(self, p4: VectorProtocolLorentz) -> SameVectorType: ...
    def boostCM_of_beta3(self, beta3: VectorProtocolSpatial) -> SameVectorType: ...
    def boostCM_of(self, booster: VectorProtocolSpatial | VectorProtocolLorentz) -> SameVectorType: ...
    def boostX(self, beta: ScalarCollection | None = None, gamma: ScalarCollection | None = None) -> SameVectorType: ...
    def boostY(self, beta: ScalarCollection | None = None, gamma: ScalarCollection | None = None) -> SameVectorType: ...
    def boostZ(self, beta: ScalarCollection | None = None, gamma: ScalarCollection | None = None) -> SameVectorType: ...
    def transform4D(self, obj: TransformProtocol4D) -> SameVectorType: ...
    def to_beta3(self) -> VectorProtocolSpatial: ...
    def is_timelike(self, tolerance: ScalarCollection = 0) -> BoolCollection: ...
    def is_spacelike(self, tolerance: ScalarCollection = 0) -> BoolCollection: ...
    def is_lightlike(self, tolerance: ScalarCollection = 1e-05) -> BoolCollection: ...

class MomentumProtocolPlanar(VectorProtocolPlanar):
    @property
    def px(self) -> ScalarCollection: ...
    @property
    def py(self) -> ScalarCollection: ...
    @property
    def pt(self) -> ScalarCollection: ...
    @property
    def pt2(self) -> ScalarCollection: ...

class MomentumProtocolSpatial(VectorProtocolSpatial, MomentumProtocolPlanar):
    @property
    def pz(self) -> ScalarCollection: ...
    @property
    def pseudorapidity(self) -> ScalarCollection: ...
    @property
    def p(self) -> ScalarCollection: ...
    @property
    def p2(self) -> ScalarCollection: ...

class MomentumProtocolLorentz(VectorProtocolLorentz, MomentumProtocolSpatial):
    @property
    def E(self) -> ScalarCollection: ...
    @property
    def e(self) -> ScalarCollection: ...
    @property
    def energy(self) -> ScalarCollection: ...
    @property
    def E2(self) -> ScalarCollection: ...
    @property
    def e2(self) -> ScalarCollection: ...
    @property
    def energy2(self) -> ScalarCollection: ...
    @property
    def M(self) -> ScalarCollection: ...
    @property
    def m(self) -> ScalarCollection: ...
    @property
    def mass(self) -> ScalarCollection: ...
    @property
    def M2(self) -> ScalarCollection: ...
    @property
    def m2(self) -> ScalarCollection: ...
    @property
    def mass2(self) -> ScalarCollection: ...
    @property
    def Et(self) -> ScalarCollection: ...
    @property
    def et(self) -> ScalarCollection: ...
    @property
    def transverse_energy(self) -> ScalarCollection: ...
    @property
    def Et2(self) -> ScalarCollection: ...
    @property
    def et2(self) -> ScalarCollection: ...
    @property
    def transverse_energy2(self) -> ScalarCollection: ...
    @property
    def Mt(self) -> ScalarCollection: ...
    @property
    def mt(self) -> ScalarCollection: ...
    @property
    def transverse_mass(self) -> ScalarCollection: ...
    @property
    def Mt2(self) -> ScalarCollection: ...
    @property
    def mt2(self) -> ScalarCollection: ...
    @property
    def transverse_mass2(self) -> ScalarCollection: ...

class Vector(VectorProtocol):
    @typing.overload
    def __new__(cls, *, x: float, y: float) -> vector.VectorObject2D: ...
    @typing.overload
    def __new__(cls, *, rho: float, phi: float) -> vector.VectorObject2D: ...
    @typing.overload
    def __new__(cls, *, x: float, y: float, z: float) -> vector.VectorObject3D: ...
    @typing.overload
    def __new__(cls, *, x: float, y: float, eta: float) -> vector.VectorObject3D: ...
    @typing.overload
    def __new__(cls, *, x: float, y: float, theta: float) -> vector.VectorObject3D: ...
    @typing.overload
    def __new__(cls, *, rho: float, phi: float, z: float) -> vector.VectorObject3D: ...
    @typing.overload
    def __new__(cls, *, rho: float, phi: float, eta: float) -> vector.VectorObject3D: ...
    @typing.overload
    def __new__(cls, *, rho: float, phi: float, theta: float) -> vector.VectorObject3D: ...
    @typing.overload
    def __new__(cls, *, px: float, py: float) -> vector.MomentumObject2D: ...
    @typing.overload
    def __new__(cls, *, x: float, py: float) -> vector.MomentumObject2D: ...
    @typing.overload
    def __new__(cls, *, px: float, y: float) -> vector.MomentumObject2D: ...
    @typing.overload
    def __new__(cls, *, pt: float, phi: float) -> vector.MomentumObject2D: ...
    @typing.overload
    def __new__(cls, *, x: float, y: float, pz: float) -> vector.MomentumObject3D: ...
    @typing.overload
    def __new__(cls, *, x: float, py: float, z: float) -> vector.MomentumObject3D: ...
    @typing.overload
    def __new__(cls, *, x: float, py: float, pz: float) -> vector.MomentumObject3D: ...
    @typing.overload
    def __new__(cls, *, px: float, y: float, z: float) -> vector.MomentumObject3D: ...
    @typing.overload
    def __new__(cls, *, px: float, y: float, pz: float) -> vector.MomentumObject3D: ...
    @typing.overload
    def __new__(cls, *, px: float, py: float, z: float) -> vector.MomentumObject3D: ...
    @typing.overload
    def __new__(cls, *, px: float, py: float, pz: float) -> vector.MomentumObject3D: ...
    @typing.overload
    def __new__(cls, *, rho: float, phi: float, pz: float) -> vector.MomentumObject3D: ...
    @typing.overload
    def __new__(cls, *, pt: float, phi: float, z: float) -> vector.MomentumObject3D: ...
    @typing.overload
    def __new__(cls, *, pt: float, phi: float, pz: float) -> vector.MomentumObject3D: ...
    @typing.overload
    def __new__(cls, *, x: float, py: float, theta: float) -> vector.MomentumObject3D: ...
    @typing.overload
    def __new__(cls, *, px: float, y: float, theta: float) -> vector.MomentumObject3D: ...
    @typing.overload
    def __new__(cls, *, px: float, py: float, theta: float) -> vector.MomentumObject3D: ...
    @typing.overload
    def __new__(cls, *, pt: float, phi: float, theta: float) -> vector.MomentumObject3D: ...
    @typing.overload
    def __new__(cls, *, x: float, py: float, eta: float) -> vector.MomentumObject3D: ...
    @typing.overload
    def __new__(cls, *, px: float, y: float, eta: float) -> vector.MomentumObject3D: ...
    @typing.overload
    def __new__(cls, *, px: float, py: float, eta: float) -> vector.MomentumObject3D: ...
    @typing.overload
    def __new__(cls, *, pt: float, phi: float, eta: float) -> vector.MomentumObject3D: ...
    @typing.overload
    def __new__(cls, *, x: float, y: float, z: float, t: float) -> vector.VectorObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, y: float, pz: float, t: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, py: float, z: float, t: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, py: float, pz: float, t: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, y: float, z: float, t: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, y: float, pz: float, t: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, py: float, z: float, t: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, py: float, pz: float, t: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, rho: float, phi: float, z: float, t: float) -> vector.VectorObject4D: ...
    @typing.overload
    def __new__(cls, *, rho: float, phi: float, pz: float, t: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, pt: float, phi: float, z: float, t: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, pt: float, phi: float, pz: float, t: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, y: float, theta: float, t: float) -> vector.VectorObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, py: float, theta: float, t: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, y: float, theta: float, t: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, py: float, theta: float, t: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, rho: float, phi: float, theta: float, t: float) -> vector.VectorObject4D: ...
    @typing.overload
    def __new__(cls, *, pt: float, phi: float, theta: float, t: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, y: float, eta: float, t: float) -> vector.VectorObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, py: float, eta: float, t: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, y: float, eta: float, t: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, py: float, eta: float, t: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, rho: float, phi: float, eta: float, t: float) -> vector.VectorObject4D: ...
    @typing.overload
    def __new__(cls, *, pt: float, phi: float, eta: float, t: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, y: float, z: float, tau: float) -> vector.VectorObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, y: float, pz: float, tau: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, py: float, z: float, tau: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, py: float, pz: float, tau: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, y: float, z: float, tau: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, y: float, pz: float, tau: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, py: float, z: float, tau: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, py: float, pz: float, tau: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, rho: float, phi: float, z: float, tau: float) -> vector.VectorObject4D: ...
    @typing.overload
    def __new__(cls, *, rho: float, phi: float, pz: float, tau: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, ptau: float, phi: float, z: float, tau: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, ptau: float, phi: float, pz: float, tau: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, y: float, theta: float, tau: float) -> vector.VectorObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, py: float, theta: float, tau: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, y: float, theta: float, tau: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, py: float, theta: float, tau: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, rho: float, phi: float, theta: float, tau: float) -> vector.VectorObject4D: ...
    @typing.overload
    def __new__(cls, *, ptau: float, phi: float, theta: float, tau: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, y: float, eta: float, tau: float) -> vector.VectorObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, py: float, eta: float, tau: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, y: float, eta: float, tau: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, py: float, eta: float, tau: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, rho: float, phi: float, eta: float, tau: float) -> vector.VectorObject4D: ...
    @typing.overload
    def __new__(cls, *, ptau: float, phi: float, eta: float, tau: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, y: float, z: float, E: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, y: float, pz: float, E: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, py: float, z: float, E: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, py: float, pz: float, E: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, y: float, z: float, E: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, y: float, pz: float, E: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, py: float, z: float, E: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, py: float, pz: float, E: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, rho: float, phi: float, z: float, E: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, rho: float, phi: float, pz: float, E: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, pE: float, phi: float, z: float, E: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, pE: float, phi: float, pz: float, E: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, y: float, theta: float, E: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, py: float, theta: float, E: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, y: float, theta: float, E: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, py: float, theta: float, E: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, rho: float, phi: float, theta: float, E: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, pE: float, phi: float, theta: float, E: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, y: float, eta: float, E: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, py: float, eta: float, E: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, y: float, eta: float, E: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, py: float, eta: float, E: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, rho: float, phi: float, eta: float, E: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, pE: float, phi: float, eta: float, E: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, y: float, z: float, e: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, y: float, pz: float, e: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, py: float, z: float, e: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, py: float, pz: float, e: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, y: float, z: float, e: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, y: float, pz: float, e: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, py: float, z: float, e: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, py: float, pz: float, e: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, rho: float, phi: float, z: float, e: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, rho: float, phi: float, pz: float, e: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, pe: float, phi: float, z: float, e: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, pe: float, phi: float, pz: float, e: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, y: float, theta: float, e: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, py: float, theta: float, e: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, y: float, theta: float, e: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, py: float, theta: float, e: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, rho: float, phi: float, theta: float, e: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, pe: float, phi: float, theta: float, e: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, y: float, eta: float, e: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, py: float, eta: float, e: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, y: float, eta: float, e: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, py: float, eta: float, e: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, rho: float, phi: float, eta: float, e: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, pe: float, phi: float, eta: float, e: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, y: float, z: float, energy: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, y: float, pz: float, energy: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, py: float, z: float, energy: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, py: float, pz: float, energy: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, y: float, z: float, energy: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, y: float, pz: float, energy: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, py: float, z: float, energy: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, py: float, pz: float, energy: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, rho: float, phi: float, z: float, energy: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, rho: float, phi: float, pz: float, energy: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, pt: float, phi: float, z: float, energy: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, pt: float, phi: float, pz: float, energy: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, y: float, theta: float, energy: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, py: float, theta: float, energy: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, y: float, theta: float, energy: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, py: float, theta: float, energy: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, rho: float, phi: float, theta: float, energy: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, pt: float, phi: float, theta: float, energy: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, y: float, eta: float, energy: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, py: float, eta: float, energy: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, y: float, eta: float, energy: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, py: float, eta: float, energy: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, rho: float, phi: float, eta: float, energy: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, pt: float, phi: float, eta: float, energy: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, y: float, z: float, M: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, y: float, pz: float, M: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, py: float, z: float, M: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, py: float, pz: float, M: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, y: float, z: float, M: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, y: float, pz: float, M: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, py: float, z: float, M: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, py: float, pz: float, M: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, rho: float, phi: float, z: float, M: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, rho: float, phi: float, pz: float, M: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, pM: float, phi: float, z: float, M: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, pM: float, phi: float, pz: float, M: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, y: float, theta: float, M: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, py: float, theta: float, M: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, y: float, theta: float, M: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, py: float, theta: float, M: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, rho: float, phi: float, theta: float, M: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, pM: float, phi: float, theta: float, M: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, y: float, eta: float, M: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, py: float, eta: float, M: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, y: float, eta: float, M: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, py: float, eta: float, M: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, rho: float, phi: float, eta: float, M: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, pM: float, phi: float, eta: float, M: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, y: float, z: float, m: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, y: float, pz: float, m: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, py: float, z: float, m: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, py: float, pz: float, m: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, y: float, z: float, m: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, y: float, pz: float, m: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, py: float, z: float, m: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, py: float, pz: float, m: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, rho: float, phi: float, z: float, m: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, rho: float, phi: float, pz: float, m: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, pm: float, phi: float, z: float, m: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, pm: float, phi: float, pz: float, m: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, y: float, theta: float, m: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, py: float, theta: float, m: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, y: float, theta: float, m: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, py: float, theta: float, m: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, rho: float, phi: float, theta: float, m: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, pm: float, phi: float, theta: float, m: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, y: float, eta: float, m: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, py: float, eta: float, m: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, y: float, eta: float, m: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, py: float, eta: float, m: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, rho: float, phi: float, eta: float, m: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, pm: float, phi: float, eta: float, m: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, y: float, z: float, mass: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, y: float, pz: float, mass: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, py: float, z: float, mass: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, py: float, pz: float, mass: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, y: float, z: float, mass: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, y: float, pz: float, mass: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, py: float, z: float, mass: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, py: float, pz: float, mass: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, rho: float, phi: float, z: float, mass: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, rho: float, phi: float, pz: float, mass: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, pt: float, phi: float, z: float, mass: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, pt: float, phi: float, pz: float, mass: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, y: float, theta: float, mass: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, py: float, theta: float, mass: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, y: float, theta: float, mass: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, py: float, theta: float, mass: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, rho: float, phi: float, theta: float, mass: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, pt: float, phi: float, theta: float, mass: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, y: float, eta: float, mass: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, x: float, py: float, eta: float, mass: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, y: float, eta: float, mass: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, px: float, py: float, eta: float, mass: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, rho: float, phi: float, eta: float, mass: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, *, pt: float, phi: float, eta: float, mass: float) -> vector.MomentumObject4D: ...
    @typing.overload
    def __new__(cls, /, __azimuthal: Azimuthal) -> Vector: ...
    @typing.overload
    def __new__(cls, __azimuthal: Azimuthal, /, __longitudinal: Longitudinal) -> Vector: ...
    @typing.overload
    def __new__(cls, __azimuthal: Azimuthal, __longitudinal: Longitudinal, /, __temporal: Temporal) -> Vector: ...
    def to_xy(self) -> VectorProtocolPlanar: ...
    def to_pxpy(self) -> VectorProtocolPlanar: ...
    def to_rhophi(self) -> VectorProtocolPlanar: ...
    def to_ptphi(self) -> VectorProtocolPlanar: ...
    def to_xyz(self, *, z: float | FloatArray = 0.0) -> VectorProtocolSpatial: ...
    def to_xytheta(self, *, theta: float | FloatArray = 0.0) -> VectorProtocolSpatial: ...
    def to_xyeta(self, *, eta: float | FloatArray = 0.0) -> VectorProtocolSpatial: ...
    def to_pxpypz(self, *, pz: float | FloatArray = 0.0) -> VectorProtocolSpatial: ...
    def to_pxpytheta(self, *, theta: float | FloatArray = 0.0) -> VectorProtocolSpatial: ...
    def to_pxpyeta(self, *, eta: float | FloatArray = 0.0) -> VectorProtocolSpatial: ...
    def to_rhophiz(self, *, z: float | FloatArray = 0.0) -> VectorProtocolSpatial: ...
    def to_rhophitheta(self, *, theta: float | FloatArray = 0.0) -> VectorProtocolSpatial: ...
    def to_rhophieta(self, *, eta: float | FloatArray = 0.0) -> VectorProtocolSpatial: ...
    def to_ptphipz(self, *, pz: float | FloatArray = 0.0) -> VectorProtocolSpatial: ...
    def to_ptphitheta(self, *, theta: float | FloatArray = 0.0) -> VectorProtocolSpatial: ...
    def to_ptphieta(self, *, eta: float | FloatArray = 0.0) -> VectorProtocolSpatial: ...
    def to_xyzt(self, *, z: float | FloatArray = 0.0, t: float | FloatArray = 0.0) -> VectorProtocolLorentz: ...
    def to_xyztau(self, *, z: float | FloatArray = 0.0, tau: float | FloatArray = 0.0) -> VectorProtocolLorentz: ...
    def to_xythetat(self, *, theta: float | FloatArray = 0.0, t: float | FloatArray = 0.0) -> VectorProtocolLorentz: ...
    def to_xythetatau(self, *, theta: float | FloatArray = 0.0, tau: float | FloatArray = 0.0) -> VectorProtocolLorentz: ...
    def to_xyetat(self, *, eta: float | FloatArray = 0.0, t: float | FloatArray = 0.0) -> VectorProtocolLorentz: ...
    def to_xyetatau(self, *, eta: float | FloatArray = 0.0, tau: float | FloatArray = 0.0) -> VectorProtocolLorentz: ...
    def to_pxpypzenergy(self, *, pz: float | FloatArray = 0.0, energy: float | FloatArray = 0.0) -> VectorProtocolLorentz: ...
    def to_pxpythetaenergy(self, *, theta: float | FloatArray = 0.0, energy: float | FloatArray = 0.0) -> VectorProtocolLorentz: ...
    def to_pxpyetaenergy(self, *, eta: float | FloatArray = 0.0, energy: float | FloatArray = 0.0) -> VectorProtocolLorentz: ...
    def to_pxpypzmass(self, *, pz: float | FloatArray = 0.0, mass: float | FloatArray = 0.0) -> VectorProtocolLorentz: ...
    def to_pxpythetamass(self, *, theta: float | FloatArray = 0.0, mass: float | FloatArray = 0.0) -> VectorProtocolLorentz: ...
    def to_pxpyetamass(self, *, eta: float | FloatArray = 0.0, mass: float | FloatArray = 0.0) -> VectorProtocolLorentz: ...
    def to_rhophizt(self, *, z: float | FloatArray = 0.0, t: float | FloatArray = 0.0) -> VectorProtocolLorentz: ...
    def to_rhophiztau(self, *, z: float | FloatArray = 0.0, tau: float | FloatArray = 0.0) -> VectorProtocolLorentz: ...
    def to_rhophithetat(self, *, theta: float | FloatArray = 0.0, t: float | FloatArray = 0.0) -> VectorProtocolLorentz: ...
    def to_rhophithetatau(self, *, theta: float | FloatArray = 0.0, tau: float | FloatArray = 0.0) -> VectorProtocolLorentz: ...
    def to_rhophietat(self, *, eta: float | FloatArray = 0.0, t: float | FloatArray = 0.0) -> VectorProtocolLorentz: ...
    def to_rhophietatau(self, *, eta: float | FloatArray = 0.0, tau: float | FloatArray = 0.0) -> VectorProtocolLorentz: ...
    def to_ptphipzenergy(self, *, pz: float | FloatArray = 0.0, energy: float | FloatArray = 0.0) -> VectorProtocolLorentz: ...
    def to_ptphithetaenergy(self, *, theta: float | FloatArray = 0.0, energy: float | FloatArray = 0.0) -> VectorProtocolLorentz: ...
    def to_ptphietaenergy(self, *, eta: float | FloatArray = 0.0, energy: float | FloatArray = 0.0) -> VectorProtocolLorentz: ...
    def to_ptphipzmass(self, *, pz: float | FloatArray = 0.0, mass: float | FloatArray = 0.0) -> VectorProtocolLorentz: ...
    def to_ptphithetamass(self, *, theta: float | FloatArray = 0.0, mass: float | FloatArray = 0.0) -> VectorProtocolLorentz: ...
    def to_ptphietamass(self, *, eta: float | FloatArray = 0.0, mass: float | FloatArray = 0.0) -> VectorProtocolLorentz: ...
    def like(self, other: VectorProtocol) -> VectorProtocol: ...

class Vector2D(Vector, VectorProtocolPlanar):
    def to_Vector2D(self) -> VectorProtocolPlanar: ...
    def to_Vector3D(self, *, z: float | FloatArray | None = None, pz: float | FloatArray | None = None, theta: float | FloatArray | None = None, eta: float | FloatArray | None = None) -> VectorProtocolSpatial: ...
    def to_Vector4D(self, *, z: float | FloatArray | None = None, pz: float | FloatArray | None = None, theta: float | FloatArray | None = None, eta: float | FloatArray | None = None, t: float | FloatArray | None = None, e: float | FloatArray | None = None, E: float | FloatArray | None = None, energy: float | FloatArray | None = None, tau: float | FloatArray | None = None, m: float | FloatArray | None = None, M: float | FloatArray | None = None, mass: float | FloatArray | None = None) -> VectorProtocolLorentz: ...
    def to_2D(self) -> VectorProtocolPlanar: ...
    def to_3D(self, **kwargs: float | None) -> VectorProtocolSpatial: ...
    def to_4D(self, **kwargs: float | None) -> VectorProtocolLorentz: ...

class Vector3D(Vector, VectorProtocolSpatial):
    def to_Vector2D(self) -> VectorProtocolPlanar: ...
    def to_Vector3D(self) -> VectorProtocolSpatial: ...
    def to_Vector4D(self, *, t: float | FloatArray | None = None, e: float | FloatArray | None = None, E: float | FloatArray | None = None, energy: float | FloatArray | None = None, tau: float | FloatArray | None = None, m: float | FloatArray | None = None, M: float | FloatArray | None = None, mass: float | FloatArray | None = None) -> VectorProtocolLorentz: ...
    def to_2D(self) -> VectorProtocolPlanar: ...
    def to_3D(self) -> VectorProtocolSpatial: ...
    def to_4D(self, **kwargs: float | None) -> VectorProtocolLorentz: ...

class Vector4D(Vector, VectorProtocolLorentz):
    def to_Vector2D(self) -> VectorProtocolPlanar: ...
    def to_Vector3D(self) -> VectorProtocolSpatial: ...
    def to_Vector4D(self) -> VectorProtocolLorentz: ...
    def to_2D(self) -> VectorProtocolPlanar: ...
    def to_3D(self) -> VectorProtocolSpatial: ...
    def to_4D(self) -> VectorProtocolLorentz: ...

class Planar(VectorProtocolPlanar):
    @property
    def x(self) -> ScalarCollection: ...
    @property
    def y(self) -> ScalarCollection: ...
    @property
    def rho(self) -> ScalarCollection: ...
    @property
    def rho2(self) -> ScalarCollection: ...
    @property
    def phi(self) -> ScalarCollection: ...
    def deltaphi(self, other: VectorProtocol) -> ScalarCollection: ...
    def rotateZ(self, angle: ScalarCollection) -> SameVectorType: ...
    def transform2D(self, obj: TransformProtocol2D) -> SameVectorType: ...
    def is_parallel(self, other: VectorProtocol, tolerance: ScalarCollection = 1e-05) -> BoolCollection: ...
    def is_antiparallel(self, other: VectorProtocol, tolerance: ScalarCollection = 1e-05) -> BoolCollection: ...
    def is_perpendicular(self, other: VectorProtocol, tolerance: ScalarCollection = 1e-05) -> BoolCollection: ...
    def unit(self) -> SameVectorType: ...
    def dot(self, other: VectorProtocol) -> ScalarCollection: ...
    def add(self, other: VectorProtocol) -> VectorProtocol: ...
    def subtract(self, other: VectorProtocol) -> VectorProtocol: ...
    @property
    def neg2D(self) -> SameVectorType: ...
    def scale2D(self, factor: ScalarCollection) -> SameVectorType: ...
    def scale(self, factor: ScalarCollection) -> SameVectorType: ...
    def equal(self, other: VectorProtocol) -> BoolCollection: ...
    def not_equal(self, other: VectorProtocol) -> BoolCollection: ...
    def isclose(self, other: VectorProtocol, rtol: ScalarCollection = 1e-05, atol: ScalarCollection = 1e-08, equal_nan: BoolCollection = False) -> BoolCollection: ...

class Spatial(Planar, VectorProtocolSpatial):
    @property
    def z(self) -> ScalarCollection: ...
    @property
    def theta(self) -> ScalarCollection: ...
    @property
    def eta(self) -> ScalarCollection: ...
    @property
    def costheta(self) -> ScalarCollection: ...
    @property
    def cottheta(self) -> ScalarCollection: ...
    @property
    def mag(self) -> ScalarCollection: ...
    @property
    def mag2(self) -> ScalarCollection: ...
    def cross(self, other: VectorProtocolSpatial) -> VectorProtocolSpatial: ...
    def deltaangle(self, other: VectorProtocolSpatial | VectorProtocolLorentz) -> ScalarCollection: ...
    def deltaeta(self, other: VectorProtocolSpatial | VectorProtocolLorentz) -> ScalarCollection: ...
    def deltaR(self, other: VectorProtocolSpatial | VectorProtocolLorentz) -> ScalarCollection: ...
    def deltaR2(self, other: VectorProtocolSpatial | VectorProtocolLorentz) -> ScalarCollection: ...
    def rotateX(self, angle: ScalarCollection) -> SameVectorType: ...
    def rotateY(self, angle: ScalarCollection) -> SameVectorType: ...
    def rotate_axis(self, axis: VectorProtocolSpatial, angle: ScalarCollection) -> SameVectorType: ...
    def rotate_euler(self, phi: ScalarCollection, theta: ScalarCollection, psi: ScalarCollection, order: str = 'zxz') -> SameVectorType: ...
    def rotate_nautical(self, yaw: ScalarCollection, pitch: ScalarCollection, roll: ScalarCollection) -> SameVectorType: ...
    def rotate_quaternion(self, u: ScalarCollection, i: ScalarCollection, j: ScalarCollection, k: ScalarCollection) -> SameVectorType: ...
    def transform3D(self, obj: TransformProtocol3D) -> SameVectorType: ...
    def is_parallel(self, other: VectorProtocol, tolerance: ScalarCollection = 1e-05) -> BoolCollection: ...
    def is_antiparallel(self, other: VectorProtocol, tolerance: ScalarCollection = 1e-05) -> BoolCollection: ...
    def is_perpendicular(self, other: VectorProtocol, tolerance: ScalarCollection = 1e-05) -> BoolCollection: ...
    def unit(self) -> SameVectorType: ...
    def dot(self, other: VectorProtocol) -> ScalarCollection: ...
    def add(self, other: VectorProtocol) -> VectorProtocol: ...
    def subtract(self, other: VectorProtocol) -> VectorProtocol: ...
    @property
    def neg2D(self) -> SameVectorType: ...
    @property
    def neg3D(self) -> SameVectorType: ...
    def scale2D(self, factor: ScalarCollection) -> SameVectorType: ...
    def scale3D(self, factor: ScalarCollection) -> SameVectorType: ...
    def scale(self, factor: ScalarCollection) -> SameVectorType: ...
    def equal(self, other: VectorProtocol) -> BoolCollection: ...
    def not_equal(self, other: VectorProtocol) -> BoolCollection: ...
    def isclose(self, other: VectorProtocol, rtol: ScalarCollection = 1e-05, atol: ScalarCollection = 1e-08, equal_nan: BoolCollection = False) -> BoolCollection: ...

class Lorentz(Spatial, VectorProtocolLorentz):
    @property
    def t(self) -> ScalarCollection: ...
    @property
    def t2(self) -> ScalarCollection: ...
    @property
    def tau(self) -> ScalarCollection: ...
    @property
    def tau2(self) -> ScalarCollection: ...
    @property
    def beta(self) -> ScalarCollection: ...
    @property
    def gamma(self) -> ScalarCollection: ...
    @property
    def rapidity(self) -> ScalarCollection: ...
    def deltaRapidityPhi(self, other: VectorProtocolLorentz) -> ScalarCollection: ...
    def deltaRapidityPhi2(self, other: VectorProtocolLorentz) -> ScalarCollection: ...
    def boost_p4(self, p4: VectorProtocolLorentz) -> SameVectorType: ...
    def boost_beta3(self, beta3: VectorProtocolSpatial) -> SameVectorType: ...
    def boost(self, booster: VectorProtocolSpatial | VectorProtocolLorentz) -> SameVectorType: ...
    def boostCM_of_p4(self, p4: VectorProtocolLorentz) -> SameVectorType: ...
    def boostCM_of_beta3(self, beta3: VectorProtocolSpatial) -> SameVectorType: ...
    def boostCM_of(self, booster: VectorProtocolSpatial | VectorProtocolLorentz) -> SameVectorType: ...
    def boostX(self, beta: ScalarCollection | None = None, gamma: ScalarCollection | None = None) -> SameVectorType: ...
    def boostY(self, beta: ScalarCollection | None = None, gamma: ScalarCollection | None = None) -> SameVectorType: ...
    def boostZ(self, beta: ScalarCollection | None = None, gamma: ScalarCollection | None = None) -> SameVectorType: ...
    def transform4D(self, obj: TransformProtocol4D) -> SameVectorType: ...
    def to_beta3(self) -> VectorProtocolSpatial: ...
    def is_timelike(self, tolerance: ScalarCollection = 0) -> BoolCollection: ...
    def is_spacelike(self, tolerance: ScalarCollection = 0) -> BoolCollection: ...
    def is_lightlike(self, tolerance: ScalarCollection = 1e-05) -> BoolCollection: ...
    def unit(self) -> SameVectorType: ...
    def dot(self, other: VectorProtocol) -> ScalarCollection: ...
    def add(self, other: VectorProtocol) -> VectorProtocol: ...
    def subtract(self, other: VectorProtocol) -> VectorProtocol: ...
    @property
    def neg2D(self) -> SameVectorType: ...
    @property
    def neg3D(self) -> SameVectorType: ...
    @property
    def neg4D(self) -> SameVectorType: ...
    def scale2D(self, factor: ScalarCollection) -> SameVectorType: ...
    def scale3D(self, factor: ScalarCollection) -> SameVectorType: ...
    def scale4D(self, factor: ScalarCollection) -> SameVectorType: ...
    def scale(self, factor: ScalarCollection) -> SameVectorType: ...
    def equal(self, other: VectorProtocol) -> BoolCollection: ...
    def not_equal(self, other: VectorProtocol) -> BoolCollection: ...
    def isclose(self, other: VectorProtocol, rtol: ScalarCollection = 1e-05, atol: ScalarCollection = 1e-08, equal_nan: BoolCollection = False) -> BoolCollection: ...

class Momentum: ...

class PlanarMomentum(Momentum, MomentumProtocolPlanar):
    @property
    def px(self) -> ScalarCollection: ...
    @property
    def py(self) -> ScalarCollection: ...
    @property
    def pt(self) -> ScalarCollection: ...
    @property
    def pt2(self) -> ScalarCollection: ...

class SpatialMomentum(PlanarMomentum, MomentumProtocolSpatial):
    @property
    def pz(self) -> ScalarCollection: ...
    @property
    def pseudorapidity(self) -> ScalarCollection: ...
    @property
    def p(self) -> ScalarCollection: ...
    @property
    def p2(self) -> ScalarCollection: ...

class LorentzMomentum(SpatialMomentum, MomentumProtocolLorentz):
    @property
    def E(self) -> ScalarCollection: ...
    @property
    def e(self) -> ScalarCollection: ...
    @property
    def energy(self) -> ScalarCollection: ...
    @property
    def E2(self) -> ScalarCollection: ...
    @property
    def e2(self) -> ScalarCollection: ...
    @property
    def energy2(self) -> ScalarCollection: ...
    @property
    def M(self) -> ScalarCollection: ...
    @property
    def m(self) -> ScalarCollection: ...
    @property
    def mass(self) -> ScalarCollection: ...
    @property
    def M2(self) -> ScalarCollection: ...
    @property
    def m2(self) -> ScalarCollection: ...
    @property
    def mass2(self) -> ScalarCollection: ...
    @property
    def Et(self) -> ScalarCollection: ...
    @property
    def et(self) -> ScalarCollection: ...
    @property
    def transverse_energy(self) -> ScalarCollection: ...
    @property
    def Et2(self) -> ScalarCollection: ...
    @property
    def et2(self) -> ScalarCollection: ...
    @property
    def transverse_energy2(self) -> ScalarCollection: ...
    @property
    def Mt(self) -> ScalarCollection: ...
    @property
    def mt(self) -> ScalarCollection: ...
    @property
    def transverse_mass(self) -> ScalarCollection: ...
    @property
    def Mt2(self) -> ScalarCollection: ...
    @property
    def mt2(self) -> ScalarCollection: ...
    @property
    def transverse_mass2(self) -> ScalarCollection: ...

def dim(v: VectorProtocol) -> int: ...
