#!/usr/bin/env python3

import re
import os
import pprint
import argparse
import pandas       as pnd
import utils_noroot as utnr

from importlib.resources import files
from logzero             import logger as log

#-----------------------------------------------------------
class data:
    l_year = ['2011', '2012', '2015', '2016', '2017', '2018']
    cal_dir= os.environ['CALDIR']
#-----------------------------------------------------------
def get_data(content):
    content= content.replace(' ', '')
    rgx    = r'(-?\d+\.\d+)±(\d+\.\d+)'
    mch    = re.match(rgx, content)

    if not mch:
        log.error(f'Cannot match {content} with {rgx}')
        raise

    val=mch.group(1)
    err=mch.group(2)

    return [float(val), float(err)]
#-----------------------------------------------------------
def make_json(version, filename):
    csv_path    = files('q2_data').joinpath(filename)
    df_a        = pnd.read_csv(csv_path)
    df_a.index  = data.l_year
    df_r        = df_a.applymap(get_data)
    df_t        = df_r.transpose()
    for year in data.l_year:
        df_y   = df_t[year]
        d_data = df_y.to_dict()
        json_path = f'{data.cal_dir}/qsq/{version}/{year}.json'
        log.info(f'Saving to: {json_path}')
        utnr.dump_json(d_data, json_path)
#-----------------------------------------------------------
def get_args():
    parser = argparse.ArgumentParser(description='Used to make v0 q2 parameters from RX table, already in CSV format')
    args = parser.parse_args()
#-----------------------------------------------------------
if __name__ == '__main__':
    get_args()
    make_json('vp.nom', 'kp_q2_pars.csv')
    make_json('vs.nom', 'ks_q2_pars.csv')

