#!/usr/bin/env python3

import utils_noroot as utnr
import argparse
import ROOT
import numpy
import math
import os

from rk.boundaries import boundaries

#-------------------------------------
class data:
    out_dir = None
    inp_dir = None
    version = None 
    l_kind  = None
    l_dset  = None
    l_trig  = None
    l_brem  = None

    l_all_kind = ['par', 'res']
    l_all_brem = [ 0, 1, 2 ]
    l_all_dset = [ 'r1', 'r2p1', '2017', '2018' ]
    l_all_trig = [ 'ETOS', 'GTIS' ]


    log = utnr.getLogger(__name__)
#----------------------------
def par_to_res(d_par):
    d_res = {}
    for sbin, d_fit_par in d_par.items():
        if 'inf' in sbin: 
            continue
        if d_fit_par == {}:
            sg = numpy.nan
        else:
            [sg, _] = d_fit_par['sg']

        d_res[sbin] = sg

    return d_res
#-------------------------------------
def divide(num, den):
    bad_num = isinstance(num, dict) or math.isnan(num)
    bad_den = isinstance(den, dict) or math.isnan(den)

    if bad_num and bad_den:
        return numpy.nan
    elif not bad_num and not bad_den:
        return num/den
    else:
        raise ValueError
#-------------------------------------
def calculate_ratio(d_dt_str, d_mc_str):
    d_rat_str = {}
    for key in d_dt_str.keys():
        val_dt = d_dt_str[key]
        val_mc = d_mc_str[key]

        try:
            d_rat_str[key] = divide(val_dt, val_mc)
        except ValueError:
            data.log.error(f'Cannot divide resolutions for {key}')
            data.log.error(f'Data: {val_dt}')
            data.log.error(f'MC  : {val_mc}')
            raise ValueError

    return d_rat_str
#-------------------------------------
def get_ratio(kind, brem, trig, dset):
    mc_path  = f'{data.inp_dir}/get_q2_resolutions/mc/json/{data.version}/{trig}_{dset}/{kind}_brem_{brem}.json'
    dt_path  = f'{data.inp_dir}/get_q2_resolutions/data/json/{data.version}/{trig}_{dset}/{kind}_brem_{brem}.json'

    d_mc_str = utnr.load_json(mc_path)
    d_dt_str = utnr.load_json(dt_path)

    if kind == 'par':
        d_mc_str = par_to_res(d_mc_str)
        d_dt_str = par_to_res(d_dt_str)
    else:
        d_mc_str = d_mc_str
        d_dt_str = d_dt_str

    d_rat_str = calculate_ratio(d_dt_str, d_mc_str)

    return d_rat_str
#-------------------------------------
def get_args():
    parser = argparse.ArgumentParser(description='Used to create ratio histograms and JSON files of data and MC resolutions')
    parser.add_argument('-v', '--vers', type=str , help='Version'        , required=True) 
    parser.add_argument('-b', '--brem', nargs='+', help='Brem category'  , default=data.l_all_brem) 
    parser.add_argument('-d', '--dset', nargs='+', help='Dataset'        , default=data.l_all_dset) 
    parser.add_argument('-t', '--trig', nargs='+', help='Trigger'        , default=data.l_all_trig) 
    parser.add_argument('-k', '--kind', nargs='+', help='From fit or RMS', default=data.l_all_kind) 
    args = parser.parse_args()

    data.version = args.vers
    data.l_brem  = args.brem
    data.l_dset  = args.dset
    data.l_trig  = args.trig
    data.l_kind  = args.kind

    data.out_dir = utnr.make_dir_path(f'{os.environ["QSQSYS"]}/get_q2_resolutions/ratio/{data.version}')
    data.inp_dir = os.environ['QSQSYS']
#-------------------------------------
def convert_to_hist(d_rat_str):
    s_bound = set()
    for sbound, _ in d_rat_str.items():
        bnd = boundaries(sbound)
        (p1, p2), _ = bnd.data
        s_bound.add(p1)
        s_bound.add(p2)

    l_bound = list(s_bound)
    nbin    = len(l_bound) - 1
    l_bound.sort()
    arr_bound = numpy.array(l_bound)

    hist = ROOT.TH2F('hist', '', nbin, arr_bound, nbin, arr_bound)

    for sbound, ratio in d_rat_str.items():
        bnd = boundaries(sbound)
        (p1, p2), (q1, q2) = bnd.data

        pval = 0.5 * (p1 + p2)
        qval = 0.5 * (q1 + q2)

        hist.Fill(pval, qval, ratio)

    return hist
#-------------------------------------
def main():
    get_args()
    for trig in data.l_trig:
        for dset in data.l_dset:
            map_path = f'{data.out_dir}/{dset}_{trig}.root'
            data.log.visible(f'Saving to: {map_path}')
            ofile = ROOT.TFile(map_path, 'recreate')
            for kind in data.l_kind:
                for brem in data.l_brem:
                    d_rat_str = get_ratio(kind, brem, trig, dset)
                    utnr.dump_json(d_rat_str, f'{data.out_dir}/{trig}_{dset}/{kind}_brem_{brem}.json')

                    h_rat = convert_to_hist(d_rat_str)
                    h_rat.SetName(f'h_{kind}_brem_{brem}')
                    h_rat.Write()
            ofile.Close()
#-------------------------------------
if __name__ == '__main__':
    main()

