#!/usr/bin/env python3

import argparse
import numpy
import math 
import os

import utils_noroot as utnr

from jacobi import propagate

from stats.average import average              as sta_avg
from stats.utils   import error_to_covariance  as sta_ecv
#----------------------------
class data:
    log    = utnr.getLogger(__name__)
    in_ver = None
    ot_ver = None
    l_year = None
    l_trig = None
    l_brem = None
    caldir = None 
    syst   = None
    average= None 

    input_dir  = f'{os.environ["QSQSYS"]}/get_q2_tables'
    l_all_year = ['2017', '2018'] + ['r1', 'r2p1']
    l_all_trig = ['ETOS', 'GTIS']
    l_all_syst = ['nom', 'nspd']
    l_all_brem = ['0', '1', '2']
    cal_dir    = os.environ['CALDIR']
    job_dir    = os.environ['JOBDIR']
#----------------------------
def get_args():
    parser = argparse.ArgumentParser(description='Used to perform several operations on TCKs')
    parser.add_argument('-i', '--input' ,  type=str, help='Input version', required=True)
    parser.add_argument('-o', '--output',  type=str, help='Output version', required=True)
    parser.add_argument('-y', '--year'  , nargs='+', help='Years/datasets', default=data.l_all_year, choices=data.l_all_year)
    parser.add_argument('-t', '--trig'  , nargs='+', help='Trigger'       , default=data.l_all_trig, choices=data.l_all_trig)
    parser.add_argument('-b', '--brem'  , nargs='+', help='Brem category' , default=data.l_all_brem, choices=data.l_all_brem)
    parser.add_argument('-s', '--syst'  , nargs='+', help='Systematics'   , default=data.l_all_syst, choices=data.l_all_syst)
    parser.add_argument('-a', '--avrg'  ,  type=int, help='Will average parameters over TIS and TOS', default=1, choices=[0, 1])
    parser.add_argument('-f', '--fake_run', type=int, help='If 0 will send maps to $CALDIR, if 1 will send maps to $JOBDIR', default=1, choices=[0, 1])
    args = parser.parse_args()

    data.in_ver = args.input
    data.ot_ver = args.output
    data.l_year = args.year
    data.l_trig = args.trig
    data.l_brem = args.brem
    data.l_syst = args.syst
    data.caldir = data.cal_dir if args.fake_run == 0 else data.job_dir
    data.average= args.avrg
#----------------------------
def get_nom_map(year, trig, brem):
    sim_map_path       = f'{data.input_dir}/fits/{data.in_ver}/sim_{trig}_{year}_{brem}_nom.json'
    dat_map_path       = f'{data.input_dir}/fits/{data.in_ver}/dat_{trig}_{year}_{brem}_nom.json'

    d_sim_par          = utnr.load_json(sim_map_path)
    d_dat_par          = utnr.load_json(dat_map_path)

    f_dat_mu, e_dat_mu = tuple(map(float, d_dat_par['mu']))
    f_sim_mu, e_sim_mu = tuple(map(float, d_sim_par['mu']))

    f_dat_sg, e_dat_sg = tuple(map(float, d_dat_par['sg']))
    f_sim_sg, e_sim_sg = tuple(map(float, d_sim_par['sg']))

    f_delta_m, v_delta_m = propagate(lambda x, y: x - y, f_dat_mu, e_dat_mu ** 2, f_sim_mu, e_sim_mu ** 2) 
    f_sigma_m, v_sigma_m = propagate(lambda x, y: x / y, f_dat_sg, e_dat_sg ** 2, f_sim_sg, e_sim_sg ** 2) 

    d_table                                 = {}
    d_table[f'{trig} delta_m {brem} gamma'] = [f_delta_m.tolist(), math.sqrt(v_delta_m)]
    d_table[f'{trig} s_sigma {brem} gamma'] = [f_sigma_m.tolist(), math.sqrt(v_sigma_m)]
    d_table[f'{trig} mu_MC {brem} gamma'  ] = [f_sim_mu          ,           e_sim_mu  ]

    return d_table
#----------------------------
def get_nsp_map(year, trig, brem):
    dat_map_path       = f'{data.input_dir}/fits/{data.in_ver}/dat_{trig}_{year}_{brem}_nspd.json'

    d_dat_par          = utnr.load_json(dat_map_path)

    [dl_mu_val, dl_mu_err] = d_dat_par['dmu']
    [rt_sg_val, rt_sg_err] = d_dat_par['rsg']

    l_mu_mc_val = []
    l_mu_mc_err = []
    for i_nspd in [1, 2, 3]:
        sim_map_path = f'{data.input_dir}/fits/{data.in_ver}/sim_{trig}_{year}_{brem}_{i_nspd}_nspd.json'
        d_sim_par    = utnr.load_json(sim_map_path)
        [mu_mc_val, mu_mc_err] = d_sim_par['mu']

        l_mu_mc_val.append(mu_mc_val)
        l_mu_mc_err.append(mu_mc_err)

    l_mu_mc_cov = sta_ecv(l_mu_mc_err)

    mu_mc_val, mu_mc_var = propagate(lambda x: (x[0] + x[1] + x[2])/3., l_mu_mc_val, l_mu_mc_cov) 
    mu_mc_val=mu_mc_val.tolist()
    mu_mc_err = math.sqrt(mu_mc_var)

    d_table                                 = {}
    d_table[f'{trig} delta_m {brem} gamma'] = [dl_mu_val, dl_mu_err]
    d_table[f'{trig} s_sigma {brem} gamma'] = [rt_sg_val, rt_sg_err]
    d_table[f'{trig} mu_MC {brem} gamma'  ] = [mu_mc_val, mu_mc_err]

    return d_table
#----------------------------
def get_map(year, trig, brem, syst):
    if   syst == 'nom':
        d_table = get_nom_map(year, trig, brem)
    elif syst == 'nspd':
        d_table = get_nsp_map(year, trig, brem)
    else:
        data.log.error(f'Invalid systematic: {syst}')
        raise ValueError

    return d_table
#----------------------------
def average(l_x, l_y):
    [x_val, x_err] = l_x
    [y_val, y_err] = l_y

    arr_val = numpy.array([x_val, y_val])
    arr_err = numpy.array([x_err, y_err])

    avg, err, pval = sta_avg(arr_val, arr_err)

    return [avg, err]
#----------------------------
def average_tis_tos(d_map):
    d_avg_map = {}
    for k_tos in d_map:
        if 'GTIS' in k_tos:
            continue

        k_tis = k_tos.replace('ETOS', 'GTIS')

        l_tis = d_map[k_tis]
        l_tos = d_map[k_tos]

        l_avg = average(l_tis, l_tos)

        d_avg_map[k_tis] = l_avg
        d_avg_map[k_tos] = l_avg

    return d_avg_map
#----------------------------
def merge(year):
    d_map = {}

    for trig in data.l_trig:
        for brem in data.l_brem:
            for syst in data.l_syst:
                d_tmp=get_map(year, trig, brem, syst)
                d_map.update(d_tmp)

    if   data.average == 1 and len(data.l_trig) == 2:
        d_map=average_tis_tos(d_map)
    elif data.average == 1 and len(data.l_trig) == 1:
        data.log.warning(f'Cannot average over multiple trigger categories, using only: {data.l_trig}')
    else:
        data.log.warning(f'Not averaging scales')

    map_dir  = utnr.make_dir_path(f'{data.caldir}/qsq/{data.ot_ver}')
    map_path = f'{map_dir}/{year}.json'

    data.log.visible(f'Saving to: {map_path}')
    utnr.dump_json(d_map, map_path, sort_keys=True)
#----------------------------
def main():
    get_args()
    [merge(year) for year in data.l_year]
#----------------------------
if __name__ == '__main__':
    main()

