#!/usr/bin/env python3

import os
import ROOT
import numpy
import pprint
import mplhep
import logging
import logzero
import argparse
import utils_noroot      as utnr
import matplotlib.pyplot as plt
import read_selection    as rs

from q2_syst.model import model   as q2model
from rk.q2smear    import q2smear as q2smr
from logzero       import logger  as log

#-----------------------------------
class data:
    pdf    = None
    vers   = None
    qsq_dir= None
    cas_dir= None
    cal_dir= None
    nevs   = None

    l_year = None
    l_trig = None
    l_brem = None
    nbins  = 100 

    l_all_trig = ['ETOS', 'GTIS']
    l_all_brem = ['0', '1', '2']
    l_all_year = ['2011', '2012', '2015', '2016', '2017', '2018']
#-----------------------------------
def get_rdf(trig, year, nbrem):
    data_wc = f'{data.cas_dir}/tools/apply_selection/q2_smear/ctrl/v10.18is/{year}_{trig}/*.root'

    log.debug(f'Loading files in: {data_wc}')
    
    rdf = ROOT.RDataFrame(trig, data_wc)
    if data.nevs > 0:
        total = rdf.Count().GetValue()
        log.warning(f'Picking up {data.nevs}/{total} events')
        rdf = rdf.Range(data.nevs)

    pid_cut = rs.get('pid', trig, 'jpsi', year)

    rdf=rdf.Define('brem_mult', 'L1_BremMultiplicity + L2_BremMultiplicity')
    rdf=rdf.Define('nbrem'    , 'brem_mult < 2 ? brem_mult : 2')
    rdf=rdf.Filter(f'nbrem == {nbrem}', 'BREM')
    rdf=rdf.Filter(pid_cut, 'PID')

    if data.debug:
        rep=rdf.Report()
        rep.Print()

    rdf.treename = trig

    return rdf
#-----------------------------------
def get_res_val(res, l_par):
    l_name    = [name for name in res.params]
    l_value   = res.values
    d_par_val = dict(zip(l_name, l_value)) 

    return {name : val for name, val in d_par_val.items() if name in l_par}
#-----------------------------------
def get_pdf(trig, year, nbrem):
    dat_res_path = f'{data.qsq_dir}/get_q2_tables/fits/{data.vers}/dat_{trig}_{year}_{nbrem}_nom.pkl'
    sim_res_path = f'{data.qsq_dir}/get_q2_tables/fits/{data.vers}/sim_{trig}_{year}_{nbrem}_nom.pkl'

    sim_res = utnr.load_pickle(sim_res_path)
    dat_res = utnr.load_pickle(dat_res_path)

    d_sim_par = get_res_val(sim_res, ['ap_l', 'pw_l', 'ap_r', 'pw_r', 'ncbr', 'ncbl'])
    d_dat_par = get_res_val(dat_res, ['mu', 'sg'])
    d_par     = d_sim_par | d_dat_par

    s_param   = data.pdf.get_params()

    for par in s_param:
        if par.name not in d_par:
            log.error(f'PDF parameter {par.name} not found in')
            pprint.pprint(d_par)
            raise

        val = d_par[par.name]
        par.set_value(val)
        log.debug(f'{par.name:<20}{"->":<20}{val:20.3f}')

    return data.pdf
#-----------------------------------
def plot(arr_smr, arr_org, pdf, title, name):
    arr_x = numpy.linspace(data.min_mass, data.max_mass, 400)
    arr_y = data.pdf.pdf(arr_x)

    plt.subplots(figsize=(10,7))
    plt.plot(arr_x, arr_y, '-', label='Data', color='black')
    plt.hist(arr_org, data.nbins, range=(data.min_mass, data.max_mass), histtype='step', label='Original', density=True)
    plt.hist(arr_smr, data.nbins, range=(data.min_mass, data.max_mass), histtype='step', label='Smeared' , density=True)

    plot_path = f'{data.plot_dir}/{name}.png'
    log.info(f'Saving to: {plot_path}')

    plt.legend()
    plt.grid()
    plt.title(title)
    plt.xlabel('$M(J/\psi)$')
    plt.ylabel('Normalized')
    plt.savefig(plot_path)
    plt.close('all')
#-----------------------------------
def validate(trig, year, nbrem):
    rdf = get_rdf(trig, year, nbrem)
    pdf = get_pdf(trig, year, nbrem)

    q2dir   = f'{data.cal_dir}/qsq/{data.vers}'

    smr     = q2smr(rdf, q2dir)
    arr_smr = smr.get_q2_smear(0)
    arr_org = rdf.AsNumpy(['Jpsi_M'])['Jpsi_M']
    title   = f'Trig: {trig}; Year: {year}; Brem: {nbrem}; Vers: {data.vers}'
    name    = f'{trig}_{year}_{nbrem}.png' 

    plot(arr_smr, arr_org, pdf, title, name)
#-----------------------------------
def get_args():
    parser = argparse.ArgumentParser(description='Used to compare smeared MC with fitted data') 
    parser.add_argument('-v', '--vers' , type=str, help='Version of smearing parameters and corresponding fits', required=True)
    parser.add_argument('-y', '--year' , nargs='+', help='Years'        , choices=data.l_all_year, default=data.l_all_year)
    parser.add_argument('-t', '--trig' , nargs='+', help='Triggers'     , choices=data.l_all_trig, default=data.l_all_trig)
    parser.add_argument('-b', '--brem' , nargs='+', help='Brem category', choices=data.l_all_brem, default=data.l_all_brem)
    parser.add_argument('-d', '--debug', help='Will run in debug mode'  , action='store_true')
    parser.add_argument('-e', '--nevs' , type =int, help='Number of entries to run over', default=-1)
    args = parser.parse_args()

    data.vers   = args.vers
    data.nevs   = args.nevs
    data.l_year = args.year
    data.l_trig = args.trig
    data.l_brem = args.brem

    data.qsq_dir = get_env_var('QSQSYS')
    data.cas_dir = get_env_var('CASDIR')
    data.cal_dir = get_env_var('CALDIR')

    mdl           = q2model()
    data.pdf      = mdl.get_pdf(is_signal=True, split_by_nspd=False)
    [[data.min_mass]], [[data.max_mass]] = data.pdf.space.limits

    plt.style.use(mplhep.style.LHCb2)

    data.debug = args.debug
    if args.debug:
        log.setLevel(logzero.DEBUG)
    else:
        q2smr.log.setLevel(logging.WARNING)
        log.setLevel(logzero.INFO)

    data.plot_dir = utnr.make_dir_path(f'{data.qsq_dir}/validate_smear/{data.vers}')
#-----------------------------------
def get_env_var(varname):
    try:
        value = os.environ[varname]
    except:
        log.error(f'Cannot find {varname} variable in environment')
        raise

    return value
#-----------------------------------
def main():
    for year in data.l_year:
        for trig in data.l_trig:
            for brem in data.l_brem:
                validate(trig, year, brem)
#-----------------------------------
if __name__ == '__main__':
    get_args()
    main()

