#!/usr/bin/env bash

#--------------------------------------------------
display_help()
{
    echo "Script used to steer the creation of ntuples with different decays from what is in the $RAPIDSIM_CONFIG directory"
    echo ""
    echo "-n: Number of entries in the ntuples"
}
#--------------------------------------------------
get_opts()
{
    if [[ $# -eq 0 ]]; then
        display_help
        exit 1
    fi  

    while getopts :hf:n: option; do 
        case "${option}" in
            h)  
                display_help
                exit 0
                ;;  
            n)  NEVENTS=${OPTARG};;
           \?)  echo "Invalid option: -${OPTARG}"
                display_help
                exit 1
                ;;  
            :)  echo "$0: Arguments needed"
                display_help
                exit 1
                ;;  
        esac
    done
}
# -----------------------
initialize()
{
    if [ -z $RAPIDSIM_CONFIG ];then
        echo "RAPIDSIM_CONFIG not set, this should point to directory with config files"
        exit 1
    fi

    if [ -z $RAPIDSIM_NTUPLES ];then
        echo "RAPIDSIM_NTUPLES not set, this should point to directory where ntuples will go"
        exit 1
    fi

    mkdir -p $RAPIDSIM_NTUPLES

    if [ ! -d $RAPIDSIM_NTUPLES ];then
        echo "Cannot create $RAPIDSIM_NTUPLES"
        exit 1
    fi
}
# -----------------------
find_decays()
{
    shopt -s nullglob
    PATHS=($RAPIDSIM_CONFIG/*.decay)
    FILES=("${PATHS[@]##*/}")
    DECAYS=("${FILES[@]%.decay}")
    echo "${DECAYS[@]}"
}
# -----------------------
create_config()
{
    CFG_PATH=$1
    ENERGY=$2

    echo "geometry: 4pi"              > $CFG_PATH
    echo "paramsStable : P, PT, eta" >> $CFG_PATH
    echo "energy: $ENERGY          " >> $CFG_PATH
}
# -----------------------
create_ntuple()
{
    echo "Creating $DECAY with $NEVENTS entries at $ENERGY"

    DECAYDIR=$RAPIDSIM_NTUPLES/$DECAY/$ENERGY"TeV"
    mkdir -p $DECAYDIR

    CFG_PATH=$RAPIDSIM_CONFIG/$DECAY".config"
    create_config $CFG_PATH $ENERGY

    cd $DECAYDIR
    rapidsim $RAPIDSIM_CONFIG/$DECAY $NEVENTS 1 > $DECAY".log" 2>&1
    cd -

    rm $CFG_PATH
}
# -----------------------
get_opts "$@"
initialize
find_decays

for DECAY in ${DECAYS[@]};do
    for ENERGY in "8" "13" "14";do
        create_ntuple
    done
done
