#!/usr/bin/env bash

#--------------------------------------------------
display_help()
{
    echo "Script used to steer the creation of ntuples with different decays from what is in the $RAPIDSIM_CONFIG directory"
    echo ""
    echo "-n: Number of entries in the ntuples"
    echo "-v: Version of ntuples"
}
#--------------------------------------------------
get_opts()
{
    if [[ $# -eq 0 ]]; then
        display_help
        exit 1
    fi  

    while getopts :hf:n:v: option; do 
        case "${option}" in
            h)  
                display_help
                exit 0
                ;;  
            n)  NEVENTS=${OPTARG};;
            v)  VERSION=${OPTARG};;
           \?)  echo "Invalid option: -${OPTARG}"
                display_help
                exit 1
                ;;  
            :)  echo "$0: Arguments needed"
                display_help
                exit 1
                ;;  
        esac
    done
}
# -----------------------
check_status()
{
    if [ $? -ne 0 ];then
        echo "Failed: $1"
        exit 1
    fi
}
# -----------------------
initialize()
{
    if [ -z $RAPIDSIM_CONFIG ];then
        echo "RAPIDSIM_CONFIG not set, this should point to directory with config files"
        exit 1
    fi

    if [ -z $ANADIR ];then
        echo "ANADIR variable not set"
        exit 1
    fi
}
# -----------------------
find_decays()
{
    shopt -s nullglob
    PATHS=($RAPIDSIM_CONFIG/*.decay)
    FILES=("${PATHS[@]##*/}")
    DECAYS=("${FILES[@]%.decay}")
    echo "${DECAYS[@]}"
}
# -----------------------
create_config()
{
    CFG_PATH=$1
    ENERGY=$2

    echo "geometry: 4pi"                   > $CFG_PATH
    echo "paramsStable : P, PT, eta, phi" >> $CFG_PATH
    echo "energy: $ENERGY          "      >> $CFG_PATH
}
# -----------------------
create_ntuple()
{
    echo "Creating $DECAY with $NEVENTS entries at $ENERGY"

    DECAYDIR=$ANADIR"/Rapidsim/"$DECAY"/"$ENERGY"TeV"
    mkdir -p $DECAYDIR

    check_status "Creating $DECAYDIR"

    CFG_PATH=$RAPIDSIM_CONFIG/$DECAY".config"
    create_config $CFG_PATH $ENERGY

    cd $DECAYDIR
    rapidsim $RAPIDSIM_CONFIG/$DECAY $NEVENTS 1 > $DECAY".log" 2>&1
    cd -

    rm $CFG_PATH
}
# -----------------------
get_opts "$@"
initialize
find_decays

for DECAY in ${DECAYS[@]};do
    for ENERGY in "8" "13" "14";do
        create_ntuple
    done
done
