import typing
from _typeshed import Incomplete
from vector._compute.planar import x as x, y as y
from vector._methods import AzimuthalRhoPhi as AzimuthalRhoPhi, AzimuthalXY as AzimuthalXY

def xy_xy(lib, rtol, atol, equal_nan, x1, y1, x2, y2): ...
def xy_rhophi(lib, rtol, atol, equal_nan, x1, y1, rho2, phi2): ...
def rhophi_xy(lib, rtol, atol, equal_nan, rho1, phi1, x2, y2): ...
def rhophi_rhophi(lib, rtol, atol, equal_nan, rho1, phi1, rho2, phi2): ...

dispatch_map: Incomplete

def dispatch(rtol: typing.Any, atol: typing.Any, equal_nan: typing.Any, v1: typing.Any, v2: typing.Any) -> typing.Any: ...
