import typing
from _typeshed import Incomplete
from vector._methods import AzimuthalRhoPhi as AzimuthalRhoPhi, AzimuthalXY as AzimuthalXY

def rectify(lib, phi): ...
def xy(lib, angle, x, y): ...
def rhophi(lib, angle, rho, phi): ...

dispatch_map: Incomplete

def dispatch(angle: typing.Any, v: typing.Any) -> typing.Any: ...
