import typing
from _typeshed import Incomplete
from vector._methods import AzimuthalRhoPhi as AzimuthalRhoPhi, AzimuthalXY as AzimuthalXY

def rectify(lib, phi): ...
def xy(lib, factor, x, y): ...
def rhophi(lib, factor, rho, phi): ...

dispatch_map: Incomplete

def dispatch(factor: typing.Any, v: typing.Any) -> typing.Any: ...
